"""Add new optional lib root field.

Revision ID: 01242ae7d10d
Revises: b29f7b57a860
Create Date: 2025-11-09 04:05:13.615441

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01242ae7d10d"
down_revision: str | Sequence[str] | None = "b29f7b57a860"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "libraries",
        sa.Column("library_root", sqlmodel.AutoString(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("libraries", "library_root")
    # ### end Alembic commands ###
