# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add tasks tables.

Revision ID: 09159119a222
Revises: 2486050ca863
Create Date: 2025-11-17 17:07:47.819437

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09159119a222"
down_revision: str | Sequence[str] | None = "2486050ca863"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "BOOK_UPLOAD",
                "MULTI_BOOK_UPLOAD",
                "BOOK_CONVERT",
                "BOOK_STRIP_DRM",
                "EMAIL_SEND",
                "METADATA_BACKUP",
                "THUMBNAIL_GENERATE",
                name="tasktype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="taskstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "error_message",
            sqlmodel.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("task_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tasks_type_created", "tasks", ["task_type", "created_at"], unique=False
    )
    op.create_index(
        "idx_tasks_user_status", "tasks", ["user_id", "status"], unique=False
    )
    op.create_index(op.f("ix_tasks_created_at"), "tasks", ["created_at"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_table(
        "task_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "BOOK_UPLOAD",
                "MULTI_BOOK_UPLOAD",
                "BOOK_CONVERT",
                "BOOK_STRIP_DRM",
                "EMAIL_SEND",
                "METADATA_BACKUP",
                "THUMBNAIL_GENERATE",
                name="tasktype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("avg_duration", sa.Float(), nullable=True),
        sa.Column("min_duration", sa.Float(), nullable=True),
        sa.Column("max_duration", sa.Float(), nullable=True),
        sa.Column("total_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("success_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failure_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_type"),
    )
    op.create_index(
        op.f("ix_task_statistics_updated_at"),
        "task_statistics",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_statistics_updated_at"), table_name="task_statistics")
    op.drop_table("task_statistics")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_at"), table_name="tasks")
    op.drop_index("idx_tasks_user_status", table_name="tasks")
    op.drop_index("idx_tasks_type_created", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
