# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add ebook conversion history table.

Revision ID: 0b59171fa89c
Revises: 74235b62d3e5
Create Date: 2025-11-27 08:55:40.133392

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b59171fa89c"
down_revision: str | Sequence[str] | None = "74235b62d3e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_conversions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "original_format",
            sqlmodel.AutoString(length=20),
            nullable=False,
        ),
        sa.Column("target_format", sqlmodel.AutoString(length=20), nullable=False),
        sa.Column(
            "original_file_path",
            sqlmodel.AutoString(length=2000),
            nullable=False,
        ),
        sa.Column(
            "converted_file_path",
            sqlmodel.AutoString(length=2000),
            nullable=False,
        ),
        sa.Column("original_backed_up", sa.Boolean(), nullable=False),
        sa.Column(
            "backup_file_path",
            sqlmodel.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column(
            "conversion_method",
            sa.Enum(
                "AUTO_IMPORT",
                "MANUAL",
                "KINDLE_SEND",
                name="conversionmethod",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "FAILED", name="conversionstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "book_id", "original_format", "target_format", name="uq_book_conversion"
        ),
    )
    op.create_index(
        "idx_book_conversions_book", "book_conversions", ["book_id"], unique=False
    )
    op.create_index(
        "idx_book_conversions_library_created",
        "book_conversions",
        ["library_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_book_conversions_status_created",
        "book_conversions",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_book_conversions_user_created",
        "book_conversions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_conversions_book_id"),
        "book_conversions",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_conversions_conversion_method"),
        "book_conversions",
        ["conversion_method"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_conversions_created_at"),
        "book_conversions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_conversions_library_id"),
        "book_conversions",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_conversions_original_file_path"),
        "book_conversions",
        ["original_file_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_conversions_original_format"),
        "book_conversions",
        ["original_format"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_conversions_status"), "book_conversions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_book_conversions_target_format"),
        "book_conversions",
        ["target_format"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_conversions_user_id"),
        "book_conversions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_conversions_user_id"), table_name="book_conversions")
    op.drop_index(
        op.f("ix_book_conversions_target_format"), table_name="book_conversions"
    )
    op.drop_index(op.f("ix_book_conversions_status"), table_name="book_conversions")
    op.drop_index(
        op.f("ix_book_conversions_original_format"), table_name="book_conversions"
    )
    op.drop_index(
        op.f("ix_book_conversions_original_file_path"), table_name="book_conversions"
    )
    op.drop_index(op.f("ix_book_conversions_library_id"), table_name="book_conversions")
    op.drop_index(op.f("ix_book_conversions_created_at"), table_name="book_conversions")
    op.drop_index(
        op.f("ix_book_conversions_conversion_method"), table_name="book_conversions"
    )
    op.drop_index(op.f("ix_book_conversions_book_id"), table_name="book_conversions")
    op.drop_index("idx_book_conversions_user_created", table_name="book_conversions")
    op.drop_index("idx_book_conversions_status_created", table_name="book_conversions")
    op.drop_index("idx_book_conversions_library_created", table_name="book_conversions")
    op.drop_index("idx_book_conversions_book", table_name="book_conversions")
    op.drop_table("book_conversions")
    # ### end Alembic commands ###
