# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add epubfix audit trail tables.

Revision ID: 1003fa69a604
Revises: e142ce95cf2f
Create Date: 2025-11-26 13:51:01.664296

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1003fa69a604"
down_revision: str | Sequence[str] | None = "e142ce95cf2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epub_fix_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("library_id", sa.Integer(), nullable=True),
        sa.Column("manually_triggered", sa.Boolean(), nullable=False),
        sa.Column("is_bulk_operation", sa.Boolean(), nullable=False),
        sa.Column("total_files_processed", sa.Integer(), nullable=False),
        sa.Column("total_files_fixed", sa.Integer(), nullable=False),
        sa.Column("total_fixes_applied", sa.Integer(), nullable=False),
        sa.Column("backup_enabled", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "error_message",
            sqlmodel.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_epub_fix_runs_library_created",
        "epub_fix_runs",
        ["library_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_epub_fix_runs_manually_triggered",
        "epub_fix_runs",
        ["manually_triggered", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_epub_fix_runs_user_created",
        "epub_fix_runs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epub_fix_runs_created_at"),
        "epub_fix_runs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epub_fix_runs_is_bulk_operation"),
        "epub_fix_runs",
        ["is_bulk_operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epub_fix_runs_library_id"),
        "epub_fix_runs",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epub_fix_runs_manually_triggered"),
        "epub_fix_runs",
        ["manually_triggered"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epub_fix_runs_started_at"),
        "epub_fix_runs",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epub_fix_runs_user_id"), "epub_fix_runs", ["user_id"], unique=False
    )
    op.create_table(
        "epub_fixes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("book_title", sqlmodel.AutoString(length=500), nullable=False),
        sa.Column("file_path", sqlmodel.AutoString(length=2000), nullable=False),
        sa.Column(
            "original_file_path",
            sqlmodel.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column(
            "fix_type",
            sa.Enum(
                "ENCODING",
                "BODY_ID_LINK",
                "LANGUAGE_TAG",
                "STRAY_IMG",
                name="epubfixtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("fix_description", sa.Text(), nullable=False),
        sa.Column("file_name", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("original_value", sa.Text(), nullable=True),
        sa.Column("fixed_value", sa.Text(), nullable=True),
        sa.Column("backup_created", sa.Boolean(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["epub_fix_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_epub_fixes_book_applied",
        "epub_fixes",
        ["book_id", "applied_at"],
        unique=False,
    )
    op.create_index(
        "idx_epub_fixes_file_path", "epub_fixes", ["file_path"], unique=False
    )
    op.create_index(
        "idx_epub_fixes_run_book", "epub_fixes", ["run_id", "book_id"], unique=False
    )
    op.create_index(
        "idx_epub_fixes_type_applied",
        "epub_fixes",
        ["fix_type", "applied_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epub_fixes_applied_at"), "epub_fixes", ["applied_at"], unique=False
    )
    op.create_index(
        op.f("ix_epub_fixes_book_id"), "epub_fixes", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_epub_fixes_book_title"), "epub_fixes", ["book_title"], unique=False
    )
    op.create_index(
        op.f("ix_epub_fixes_created_at"), "epub_fixes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_epub_fixes_file_path"), "epub_fixes", ["file_path"], unique=False
    )
    op.create_index(
        op.f("ix_epub_fixes_fix_type"), "epub_fixes", ["fix_type"], unique=False
    )
    op.create_index(
        op.f("ix_epub_fixes_run_id"), "epub_fixes", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_epub_fixes_run_id"), table_name="epub_fixes")
    op.drop_index(op.f("ix_epub_fixes_fix_type"), table_name="epub_fixes")
    op.drop_index(op.f("ix_epub_fixes_file_path"), table_name="epub_fixes")
    op.drop_index(op.f("ix_epub_fixes_created_at"), table_name="epub_fixes")
    op.drop_index(op.f("ix_epub_fixes_book_title"), table_name="epub_fixes")
    op.drop_index(op.f("ix_epub_fixes_book_id"), table_name="epub_fixes")
    op.drop_index(op.f("ix_epub_fixes_applied_at"), table_name="epub_fixes")
    op.drop_index("idx_epub_fixes_type_applied", table_name="epub_fixes")
    op.drop_index("idx_epub_fixes_run_book", table_name="epub_fixes")
    op.drop_index("idx_epub_fixes_file_path", table_name="epub_fixes")
    op.drop_index("idx_epub_fixes_book_applied", table_name="epub_fixes")
    op.drop_table("epub_fixes")
    op.drop_index(op.f("ix_epub_fix_runs_user_id"), table_name="epub_fix_runs")
    op.drop_index(op.f("ix_epub_fix_runs_started_at"), table_name="epub_fix_runs")
    op.drop_index(
        op.f("ix_epub_fix_runs_manually_triggered"), table_name="epub_fix_runs"
    )
    op.drop_index(op.f("ix_epub_fix_runs_library_id"), table_name="epub_fix_runs")
    op.drop_index(
        op.f("ix_epub_fix_runs_is_bulk_operation"), table_name="epub_fix_runs"
    )
    op.drop_index(op.f("ix_epub_fix_runs_created_at"), table_name="epub_fix_runs")
    op.drop_index("idx_epub_fix_runs_user_created", table_name="epub_fix_runs")
    op.drop_index("idx_epub_fix_runs_manually_triggered", table_name="epub_fix_runs")
    op.drop_index("idx_epub_fix_runs_library_created", table_name="epub_fix_runs")
    op.drop_table("epub_fix_runs")
    # ### end Alembic commands ###
