# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add openlibrary dump configs and tracking table.

Revision ID: 226a99cf4645
Revises: 34c7ece3865c
Create Date: 2025-11-20 16:35:14.933950

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "226a99cf4645"
down_revision: str | Sequence[str] | None = "34c7ece3865c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openlibrary_dump_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("authors_url", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("works_url", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("editions_url", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("default_process_authors", sa.Boolean(), nullable=False),
        sa.Column("default_process_works", sa.Boolean(), nullable=False),
        sa.Column("default_process_editions", sa.Boolean(), nullable=False),
        sa.Column("staleness_threshold_days", sa.Integer(), nullable=False),
        sa.Column("enable_auto_download", sa.Boolean(), nullable=False),
        sa.Column("enable_auto_process", sa.Boolean(), nullable=False),
        sa.Column("auto_check_interval_hours", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_openlibrary_dump_config_created_at"),
        "openlibrary_dump_config",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "openlibrary_dump_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dump_type", sqlmodel.AutoString(length=50), nullable=False),
        sa.Column("last_downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("last_processed_at", sa.DateTime(), nullable=True),
        sa.Column("file_path", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_openlibrary_dump_states_created_at"),
        "openlibrary_dump_states",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_openlibrary_dump_states_dump_type"),
        "openlibrary_dump_states",
        ["dump_type"],
        unique=True,
    )
    op.create_index(
        op.f("ix_openlibrary_dump_states_last_downloaded_at"),
        "openlibrary_dump_states",
        ["last_downloaded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_openlibrary_dump_states_last_processed_at"),
        "openlibrary_dump_states",
        ["last_processed_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Seed default configuration for OpenLibrary dumps
    now = datetime.now(UTC)
    op.execute(
        sa.text(
            """
            INSERT INTO openlibrary_dump_config (
                authors_url,
                works_url,
                editions_url,
                default_process_authors,
                default_process_works,
                default_process_editions,
                staleness_threshold_days,
                enable_auto_download,
                enable_auto_process,
                auto_check_interval_hours,
                created_at,
                updated_at
            ) VALUES (
                :authors_url,
                :works_url,
                :editions_url,
                :default_process_authors,
                :default_process_works,
                :default_process_editions,
                :staleness_threshold_days,
                :enable_auto_download,
                :enable_auto_process,
                :auto_check_interval_hours,
                :created_at,
                :updated_at
            )
            """
        ).bindparams(
            authors_url="https://openlibrary.org/data/ol_dump_authors_latest.txt.gz",
            works_url="https://openlibrary.org/data/ol_dump_works_latest.txt.gz",
            editions_url="https://openlibrary.org/data/ol_dump_editions_latest.txt.gz",
            default_process_authors=True,
            default_process_works=True,
            default_process_editions=False,
            staleness_threshold_days=30,
            enable_auto_download=True,
            enable_auto_process=True,
            auto_check_interval_hours=24,
            created_at=now,
            updated_at=now,
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_openlibrary_dump_states_last_processed_at"),
        table_name="openlibrary_dump_states",
    )
    op.drop_index(
        op.f("ix_openlibrary_dump_states_last_downloaded_at"),
        table_name="openlibrary_dump_states",
    )
    op.drop_index(
        op.f("ix_openlibrary_dump_states_dump_type"),
        table_name="openlibrary_dump_states",
    )
    op.drop_index(
        op.f("ix_openlibrary_dump_states_created_at"),
        table_name="openlibrary_dump_states",
    )
    op.drop_table("openlibrary_dump_states")
    op.drop_index(
        op.f("ix_openlibrary_dump_config_created_at"),
        table_name="openlibrary_dump_config",
    )
    op.drop_table("openlibrary_dump_config")
    # ### end Alembic commands ###
