# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add shelves tables.

Revision ID: 2486050ca863
Revises: d50f5e92f4bd
Create Date: 2025-11-13 08:20:09.916969

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2486050ca863"
down_revision: str | Sequence[str] | None = "d50f5e92f4bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shelf_archive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.AutoString(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shelf_archive_deleted_at"),
        "shelf_archive",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shelf_archive_user_id"), "shelf_archive", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_shelf_archive_uuid"), "shelf_archive", ["uuid"], unique=False
    )
    op.create_table(
        "shelves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.AutoString(length=36), nullable=False),
        sa.Column("name", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.AutoString(length=5000), nullable=True),
        sa.Column("cover_picture", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shelves_created_at"), "shelves", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_shelves_is_public"), "shelves", ["is_public"], unique=False
    )
    op.create_index(
        op.f("ix_shelves_is_active"), "shelves", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_shelves_name"), "shelves", ["name"], unique=False)
    op.create_index(op.f("ix_shelves_user_id"), "shelves", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_shelves_library_id"), "shelves", ["library_id"], unique=False
    )
    op.create_index(op.f("ix_shelves_uuid"), "shelves", ["uuid"], unique=True)
    op.create_index(
        "ix_shelves_library_id_user_id_is_public",
        "shelves",
        ["library_id", "user_id", "is_public"],
        unique=False,
    )
    op.create_index(
        "ix_shelves_library_id_name_is_public",
        "shelves",
        ["library_id", "name", "is_public"],
        unique=False,
    )
    op.create_table(
        "book_shelf_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shelf_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("date_added", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shelf_id"],
            ["shelves.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_shelf_links_book_id"),
        "book_shelf_links",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_shelf_links_date_added"),
        "book_shelf_links",
        ["date_added"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_shelf_links_order"), "book_shelf_links", ["order"], unique=False
    )
    op.create_index(
        op.f("ix_book_shelf_links_shelf_id"),
        "book_shelf_links",
        ["shelf_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_shelf_links_shelf_id"), table_name="book_shelf_links")
    op.drop_index(op.f("ix_book_shelf_links_order"), table_name="book_shelf_links")
    op.drop_index(op.f("ix_book_shelf_links_date_added"), table_name="book_shelf_links")
    op.drop_index(op.f("ix_book_shelf_links_book_id"), table_name="book_shelf_links")
    op.drop_table("book_shelf_links")
    op.drop_index("ix_shelves_library_id_name_is_public", table_name="shelves")
    op.drop_index("ix_shelves_library_id_user_id_is_public", table_name="shelves")
    op.drop_index(op.f("ix_shelves_uuid"), table_name="shelves")
    op.drop_index(op.f("ix_shelves_library_id"), table_name="shelves")
    op.drop_index(op.f("ix_shelves_user_id"), table_name="shelves")
    op.drop_index(op.f("ix_shelves_name"), table_name="shelves")
    op.drop_index(op.f("ix_shelves_is_active"), table_name="shelves")
    op.drop_index(op.f("ix_shelves_is_public"), table_name="shelves")
    op.drop_index(op.f("ix_shelves_created_at"), table_name="shelves")
    op.drop_table("shelves")
    op.drop_index(op.f("ix_shelf_archive_uuid"), table_name="shelf_archive")
    op.drop_index(op.f("ix_shelf_archive_user_id"), table_name="shelf_archive")
    op.drop_index(op.f("ix_shelf_archive_deleted_at"), table_name="shelf_archive")
    op.drop_table("shelf_archive")
    # ### end Alembic commands ###
