# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add keycloak_sub to users.

Revision ID: 3647a7e2d1ef
Revises: eacab3c0f1ab
Create Date: 2025-12-12 11:44:40.974571

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3647a7e2d1ef"
down_revision: str | None = "eacab3c0f1ab"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("keycloak_sub", sqlmodel.AutoString(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_users_keycloak_sub"), "users", ["keycloak_sub"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_keycloak_sub"), table_name="users")
    op.drop_column("users", "keycloak_sub")
    # ### end Alembic commands ###
