# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add new author works tables.

Revision ID: 72a9cf864626
Revises: b47091341845
Create Date: 2025-11-18 18:53:48.415753

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72a9cf864626"
down_revision: str | Sequence[str] | None = "b47091341845"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author_works",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_metadata_id", sa.Integer(), nullable=False),
        sa.Column("work_key", sqlmodel.AutoString(length=50), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_metadata_id"],
            ["author_metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("author_metadata_id", "work_key", name="uq_author_work"),
    )
    op.create_index(
        "idx_author_work_rank",
        "author_works",
        ["author_metadata_id", "rank"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_works_author_metadata_id"),
        "author_works",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_works_rank"), "author_works", ["rank"], unique=False
    )
    op.create_index(
        op.f("ix_author_works_work_key"), "author_works", ["work_key"], unique=False
    )
    op.create_table(
        "work_subjects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_work_id", sa.Integer(), nullable=False),
        sa.Column("subject_name", sqlmodel.AutoString(length=200), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_work_id"],
            ["author_works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("author_work_id", "subject_name", name="uq_work_subject"),
    )
    op.create_index(
        "idx_work_subject_rank",
        "work_subjects",
        ["author_work_id", "rank"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_subjects_author_work_id"),
        "work_subjects",
        ["author_work_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_subjects_rank"), "work_subjects", ["rank"], unique=False
    )
    op.create_index(
        op.f("ix_work_subjects_subject_name"),
        "work_subjects",
        ["subject_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_subjects_subject_name"), table_name="work_subjects")
    op.drop_index(op.f("ix_work_subjects_rank"), table_name="work_subjects")
    op.drop_index(op.f("ix_work_subjects_author_work_id"), table_name="work_subjects")
    op.drop_index("idx_work_subject_rank", table_name="work_subjects")
    op.drop_table("work_subjects")
    op.drop_index(op.f("ix_author_works_work_key"), table_name="author_works")
    op.drop_index(op.f("ix_author_works_rank"), table_name="author_works")
    op.drop_index(op.f("ix_author_works_author_metadata_id"), table_name="author_works")
    op.drop_index("idx_author_work_rank", table_name="author_works")
    op.drop_table("author_works")
    # ### end Alembic commands ###
