# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add comic book reading fields to progress tracker.

Revision ID: 97f0642dab85
Revises: 86366fcfad24
Create Date: 2025-12-06 07:30:26.208824

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97f0642dab85"
down_revision: str | Sequence[str] | None = "86366fcfad24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reading_progress", sa.Column("spread_mode", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "reading_progress",
        sa.Column(
            "reading_direction",
            sqlmodel.AutoString(length=20),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reading_progress", "reading_direction")
    op.drop_column("reading_progress", "spread_mode")
    # ### end Alembic commands ###
