# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add reading progress tracking tables.

Revision ID: 9cb57048d879
Revises: 74bf2dbdfcad
Create Date: 2025-11-23 12:47:41.128198

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cb57048d879"
down_revision: str | Sequence[str] | None = "74bf2dbdfcad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("format", sqlmodel.AutoString(length=10), nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("annot_id", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("annot_type", sqlmodel.AutoString(length=50), nullable=False),
        sa.Column("annot_data", sqlmodel.AutoString(), nullable=False),
        sa.Column(
            "searchable_text",
            sqlmodel.AutoString(length=5000),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_annotations_user_library_book",
        "annotations",
        ["user_id", "library_id", "book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotations_annot_id"), "annotations", ["annot_id"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_annot_type"), "annotations", ["annot_type"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_book_id"), "annotations", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_created_at"), "annotations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_format"), "annotations", ["format"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_library_id"), "annotations", ["library_id"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_timestamp"), "annotations", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_updated_at"), "annotations", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_user_id"), "annotations", ["user_id"], unique=False
    )
    op.create_table(
        "annotations_dirtied",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotations_dirtied_book_id"),
        "annotations_dirtied",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotations_dirtied_library_id"),
        "annotations_dirtied",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotations_dirtied_updated_at"),
        "annotations_dirtied",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "read_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NOT_READ", "READING", "READ", name="readstatusenum"),
            nullable=False,
        ),
        sa.Column("first_opened_at", sa.DateTime(), nullable=True),
        sa.Column("marked_as_read_at", sa.DateTime(), nullable=True),
        sa.Column("auto_marked", sa.Boolean(), nullable=False),
        sa.Column("progress_when_marked", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_read_status_status", "read_status", ["status"], unique=False)
    op.create_index(
        "idx_read_status_user_library_book",
        "read_status",
        ["user_id", "library_id", "book_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_read_status_book_id"), "read_status", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_read_status_created_at"), "read_status", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_read_status_library_id"), "read_status", ["library_id"], unique=False
    )
    op.create_index(
        op.f("ix_read_status_updated_at"), "read_status", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_read_status_user_id"), "read_status", ["user_id"], unique=False
    )
    op.create_table(
        "reading_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("format", sqlmodel.AutoString(length=10), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("cfi", sqlmodel.AutoString(length=2000), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("device", sqlmodel.AutoString(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_reading_progress_user_library_book_format",
        "reading_progress",
        ["user_id", "library_id", "book_id", "format"],
        unique=True,
    )
    op.create_index(
        op.f("ix_reading_progress_book_id"),
        "reading_progress",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_progress_format"), "reading_progress", ["format"], unique=False
    )
    op.create_index(
        op.f("ix_reading_progress_library_id"),
        "reading_progress",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_progress_updated_at"),
        "reading_progress",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_progress_user_id"),
        "reading_progress",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "reading_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("format", sqlmodel.AutoString(length=10), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("progress_start", sa.Float(), nullable=False),
        sa.Column("progress_end", sa.Float(), nullable=True),
        sa.Column("device", sqlmodel.AutoString(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_reading_sessions_started_at",
        "reading_sessions",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        "idx_reading_sessions_user_library_book",
        "reading_sessions",
        ["user_id", "library_id", "book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_sessions_book_id"),
        "reading_sessions",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_sessions_created_at"),
        "reading_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_sessions_format"), "reading_sessions", ["format"], unique=False
    )
    op.create_index(
        op.f("ix_reading_sessions_library_id"),
        "reading_sessions",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_sessions_started_at"),
        "reading_sessions",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_sessions_user_id"),
        "reading_sessions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reading_sessions_user_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_started_at"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_library_id"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_format"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_created_at"), table_name="reading_sessions")
    op.drop_index(op.f("ix_reading_sessions_book_id"), table_name="reading_sessions")
    op.drop_index(
        "idx_reading_sessions_user_library_book", table_name="reading_sessions"
    )
    op.drop_index("idx_reading_sessions_started_at", table_name="reading_sessions")
    op.drop_table("reading_sessions")
    op.drop_index(op.f("ix_reading_progress_user_id"), table_name="reading_progress")
    op.drop_index(op.f("ix_reading_progress_updated_at"), table_name="reading_progress")
    op.drop_index(op.f("ix_reading_progress_library_id"), table_name="reading_progress")
    op.drop_index(op.f("ix_reading_progress_format"), table_name="reading_progress")
    op.drop_index(op.f("ix_reading_progress_book_id"), table_name="reading_progress")
    op.drop_index(
        "idx_reading_progress_user_library_book_format", table_name="reading_progress"
    )
    op.drop_table("reading_progress")
    op.drop_index(op.f("ix_read_status_user_id"), table_name="read_status")
    op.drop_index(op.f("ix_read_status_updated_at"), table_name="read_status")
    op.drop_index(op.f("ix_read_status_library_id"), table_name="read_status")
    op.drop_index(op.f("ix_read_status_created_at"), table_name="read_status")
    op.drop_index(op.f("ix_read_status_book_id"), table_name="read_status")
    op.drop_index("idx_read_status_user_library_book", table_name="read_status")
    op.drop_index("idx_read_status_status", table_name="read_status")
    op.drop_table("read_status")
    # Drop the enum type after dropping the table that uses it
    op.execute("DROP TYPE IF EXISTS readstatusenum")
    op.drop_index(
        op.f("ix_annotations_dirtied_updated_at"), table_name="annotations_dirtied"
    )
    op.drop_index(
        op.f("ix_annotations_dirtied_library_id"), table_name="annotations_dirtied"
    )
    op.drop_index(
        op.f("ix_annotations_dirtied_book_id"), table_name="annotations_dirtied"
    )
    op.drop_table("annotations_dirtied")
    op.drop_index(op.f("ix_annotations_user_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_updated_at"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_timestamp"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_library_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_format"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_created_at"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_book_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_annot_type"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_annot_id"), table_name="annotations")
    op.drop_index("idx_annotations_user_library_book", table_name="annotations")
    op.drop_table("annotations")
    # ### end Alembic commands ###
