"""Add ereader table.

Revision ID: a5b265dab65d
Revises: 82988058a5a7
Create Date: 2025-11-07 14:46:21.760621

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5b265dab65d"
down_revision: str | Sequence[str] | None = "82988058a5a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ereader_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("device_name", sqlmodel.AutoString(length=100), nullable=True),
        sa.Column("device_type", sqlmodel.AutoString(length=50), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "preferred_format",
            sa.Enum(
                "EPUB",
                "MOBI",
                "AZW",
                "AZW3",
                "PDF",
                "TXT",
                "RTF",
                "FB2",
                "LIT",
                "LRF",
                "OEB",
                "PDB",
                "RB",
                "SNB",
                "TCR",
                name="ebookformat",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ereader_devices_created_at"),
        "ereader_devices",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ereader_devices_email"), "ereader_devices", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_ereader_devices_user_id"), "ereader_devices", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ereader_devices_user_id"), table_name="ereader_devices")
    op.drop_index(op.f("ix_ereader_devices_email"), table_name="ereader_devices")
    op.drop_index(op.f("ix_ereader_devices_created_at"), table_name="ereader_devices")
    op.drop_table("ereader_devices")
    # ### end Alembic commands ###
