# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add system config tables.

Revision ID: b29f7b57a860
Revises: a5b265dab65d
Create Date: 2025-11-07 19:48:04.390283

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b29f7b57a860"
down_revision: str | Sequence[str] | None = "a5b265dab65d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basic_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_title", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("server_port", sa.Integer(), nullable=False),
        sa.Column("external_port", sa.Integer(), nullable=True),
        sa.Column(
            "ssl_cert_file",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("ssl_key_file", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("trusted_hosts", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column(
            "log_level",
            sa.Enum(
                "DEBUG",
                "INFO",
                "WARNING",
                "ERROR",
                "CRITICAL",
                name="loglevel",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("log_file", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("enable_access_log", sa.Boolean(), nullable=False),
        sa.Column(
            "access_log_file",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("max_upload_size_mb", sa.Integer(), nullable=False),
        sa.Column("allow_anonymous_browsing", sa.Boolean(), nullable=False),
        sa.Column("allow_public_registration", sa.Boolean(), nullable=False),
        sa.Column("require_invite_for_registration", sa.Boolean(), nullable=False),
        sa.Column("require_email_for_registration", sa.Boolean(), nullable=False),
        sa.Column("allow_remote_login", sa.Boolean(), nullable=False),
        sa.Column("allow_file_uploads", sa.Boolean(), nullable=False),
        sa.Column("session_timeout_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "default_language",
            sqlmodel.AutoString(length=10),
            nullable=False,
        ),
        sa.Column(
            "default_locale",
            sqlmodel.AutoString(length=10),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_basic_config_created_at"), "basic_config", ["created_at"], unique=False
    )
    op.create_table(
        "content_restrictions_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("denied_tags", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("allowed_tags", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("restricted_column_id", sa.Integer(), nullable=True),
        sa.Column(
            "denied_column_values",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column(
            "allowed_column_values",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_restrictions_config_created_at"),
        "content_restrictions_config",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "email_server_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "server_type",
            sa.Enum("SMTP", "GMAIL", name="emailservertype", native_enum=False),
            nullable=True,
        ),
        sa.Column("smtp_host", sqlmodel.AutoString(length=255), nullable=True),
        sa.Column("smtp_port", sa.Integer(), nullable=True),
        sa.Column("smtp_username", sqlmodel.AutoString(length=255), nullable=True),
        sa.Column("smtp_password", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("smtp_use_tls", sa.Boolean(), nullable=False),
        sa.Column("smtp_use_ssl", sa.Boolean(), nullable=False),
        sa.Column(
            "smtp_from_email",
            sqlmodel.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "smtp_from_name",
            sqlmodel.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("max_email_size_mb", sa.Integer(), nullable=False),
        sa.Column("gmail_token", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_server_config_created_at"),
        "email_server_config",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "file_handling_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "calibre_binaries_dir",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column(
            "converter_path",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column(
            "kepubify_path",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("unrar_path", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column(
            "allowed_upload_formats",
            sqlmodel.AutoString(length=500),
            nullable=False,
        ),
        sa.Column("support_unicode_filenames", sa.Boolean(), nullable=False),
        sa.Column("embed_metadata", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_file_handling_config_created_at"),
        "file_handling_config",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "integration_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("google_drive_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "google_drive_folder_id",
            sqlmodel.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("google_drive_watch_token", sa.JSON(), nullable=True),
        sa.Column("goodreads_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "goodreads_api_key",
            sqlmodel.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("kobo_sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("kobo_proxy_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_integration_config_created_at"),
        "integration_config",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "ldap_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("provider_url", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("use_ssl", sa.Boolean(), nullable=False),
        sa.Column("use_tls", sa.Boolean(), nullable=False),
        sa.Column("bind_dn", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("bind_password", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("base_dn", sqlmodel.AutoString(length=500), nullable=False),
        sa.Column(
            "user_object_filter",
            sqlmodel.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "group_object_filter",
            sqlmodel.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "group_members_field",
            sqlmodel.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("group_name", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("ca_cert_path", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column(
            "client_cert_path",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column(
            "client_key_path",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("is_openldap", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ldap_config_created_at"), "ldap_config", ["created_at"], unique=False
    )
    op.create_table(
        "libraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column(
            "calibre_db_path",
            sqlmodel.AutoString(length=1000),
            nullable=False,
        ),
        sa.Column(
            "calibre_db_file",
            sqlmodel.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("calibre_uuid", sqlmodel.AutoString(length=36), nullable=True),
        sa.Column("use_split_library", sa.Boolean(), nullable=False),
        sa.Column(
            "split_library_dir",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("auto_reconnect", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_libraries_created_at"), "libraries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_libraries_is_active"), "libraries", ["is_active"], unique=False
    )
    op.create_table(
        "scheduled_tasks_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time_hour", sa.Integer(), nullable=False),
        sa.Column("duration_hours", sa.Integer(), nullable=False),
        sa.Column("generate_book_covers", sa.Boolean(), nullable=False),
        sa.Column("generate_series_covers", sa.Boolean(), nullable=False),
        sa.Column("reconnect_database", sa.Boolean(), nullable=False),
        sa.Column("metadata_backup", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_tasks_config_created_at"),
        "scheduled_tasks_config",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "security_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enable_password_policy", sa.Boolean(), nullable=False),
        sa.Column("password_min_length", sa.Integer(), nullable=False),
        sa.Column("password_require_number", sa.Boolean(), nullable=False),
        sa.Column("password_require_lowercase", sa.Boolean(), nullable=False),
        sa.Column("password_require_uppercase", sa.Boolean(), nullable=False),
        sa.Column("password_require_special", sa.Boolean(), nullable=False),
        sa.Column("session_type", sa.Integer(), nullable=False),
        sa.Column("enable_rate_limiting", sa.Boolean(), nullable=False),
        sa.Column(
            "rate_limiter_uri",
            sqlmodel.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "rate_limiter_options",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("enable_reverse_proxy_login", sa.Boolean(), nullable=False),
        sa.Column(
            "reverse_proxy_login_header",
            sqlmodel.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("check_file_extensions", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_config_created_at"),
        "security_config",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "ui_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("books_per_page", sa.Integer(), nullable=False),
        sa.Column("random_books_count", sa.Integer(), nullable=False),
        sa.Column("authors_max_display", sa.Integer(), nullable=False),
        sa.Column(
            "default_view_mode",
            sqlmodel.AutoString(length=20),
            nullable=False,
        ),
        sa.Column("theme", sqlmodel.AutoString(length=50), nullable=False),
        sa.Column("show_thumbnails", sa.Boolean(), nullable=False),
        sa.Column("thumbnail_size", sa.Integer(), nullable=False),
        sa.Column("enable_advanced_search", sa.Boolean(), nullable=False),
        sa.Column("read_column_id", sa.Integer(), nullable=True),
        sa.Column(
            "title_sort_regex",
            sqlmodel.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "columns_to_ignore",
            sqlmodel.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ui_config_created_at"), "ui_config", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ui_config_created_at"), table_name="ui_config")
    op.drop_table("ui_config")
    op.drop_index(op.f("ix_security_config_created_at"), table_name="security_config")
    op.drop_table("security_config")
    op.drop_index(
        op.f("ix_scheduled_tasks_config_created_at"),
        table_name="scheduled_tasks_config",
    )
    op.drop_table("scheduled_tasks_config")
    op.drop_index(op.f("ix_libraries_is_active"), table_name="libraries")
    op.drop_index(op.f("ix_libraries_created_at"), table_name="libraries")
    op.drop_table("libraries")
    op.drop_index(op.f("ix_ldap_config_created_at"), table_name="ldap_config")
    op.drop_table("ldap_config")
    op.drop_index(
        op.f("ix_integration_config_created_at"), table_name="integration_config"
    )
    op.drop_table("integration_config")
    op.drop_index(
        op.f("ix_file_handling_config_created_at"), table_name="file_handling_config"
    )
    op.drop_table("file_handling_config")
    op.drop_index(
        op.f("ix_email_server_config_created_at"), table_name="email_server_config"
    )
    op.drop_table("email_server_config")
    op.drop_index(
        op.f("ix_content_restrictions_config_created_at"),
        table_name="content_restrictions_config",
    )
    op.drop_table("content_restrictions_config")
    op.drop_index(op.f("ix_basic_config_created_at"), table_name="basic_config")
    op.drop_table("basic_config")
    # ### end Alembic commands ###
