# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add authors data models.

Revision ID: b47091341845
Revises: 09159119a222
Create Date: 2025-11-18 14:46:51.242395

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b47091341845"
down_revision: str | Sequence[str] | None = "09159119a222"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "openlibrary_key",
            sqlmodel.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.AutoString(length=500), nullable=False),
        sa.Column("personal_name", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("fuller_name", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("title", sqlmodel.AutoString(length=100), nullable=True),
        sa.Column("birth_date", sqlmodel.AutoString(length=100), nullable=True),
        sa.Column("death_date", sqlmodel.AutoString(length=100), nullable=True),
        sa.Column("entity_type", sqlmodel.AutoString(length=50), nullable=True),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column("location", sqlmodel.AutoString(length=200), nullable=True),
        sa.Column("photo_url", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("work_count", sa.Integer(), nullable=True),
        sa.Column("ratings_average", sa.Float(), nullable=True),
        sa.Column("ratings_count", sa.Integer(), nullable=True),
        sa.Column("top_work", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_author_metadata_name", "author_metadata", ["name"], unique=False
    )
    op.create_index(
        "idx_author_metadata_openlibrary_key",
        "author_metadata",
        ["openlibrary_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_metadata_created_at"),
        "author_metadata",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_metadata_name"), "author_metadata", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_author_metadata_openlibrary_key"),
        "author_metadata",
        ["openlibrary_key"],
        unique=True,
    )
    op.create_table(
        "author_alternate_names",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_metadata_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_metadata_id"],
            ["author_metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "author_metadata_id", "name", name="uq_author_alternate_name"
        ),
    )
    op.create_index(
        op.f("ix_author_alternate_names_author_metadata_id"),
        "author_alternate_names",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_alternate_names_name"),
        "author_alternate_names",
        ["name"],
        unique=False,
    )
    op.create_table(
        "author_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_metadata_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.AutoString(length=200), nullable=False),
        sa.Column("url", sqlmodel.AutoString(length=1000), nullable=False),
        sa.Column("link_type", sqlmodel.AutoString(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_metadata_id"],
            ["author_metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_author_links_author_metadata_id"),
        "author_links",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_table(
        "author_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("calibre_author_id", sa.Integer(), nullable=False),
        sa.Column("author_metadata_id", sa.Integer(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("matched_by", sqlmodel.AutoString(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_metadata_id"],
            ["author_metadata.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_author_mappings_library_id"),
        "author_mappings",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        "idx_author_mapping_calibre",
        "author_mappings",
        ["calibre_author_id"],
        unique=False,
    )
    op.create_index(
        "idx_author_mapping_metadata",
        "author_mappings",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_index(
        "idx_author_mapping_verified", "author_mappings", ["is_verified"], unique=False
    )
    op.create_index(
        op.f("ix_author_mappings_author_metadata_id"),
        "author_mappings",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_mappings_calibre_author_id"),
        "author_mappings",
        ["calibre_author_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_author_mappings_created_at"),
        "author_mappings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_mappings_is_verified"),
        "author_mappings",
        ["is_verified"],
        unique=False,
    )
    op.create_table(
        "author_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_metadata_id", sa.Integer(), nullable=False),
        sa.Column("openlibrary_photo_id", sa.Integer(), nullable=True),
        sa.Column("photo_url", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_metadata_id"],
            ["author_metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_author_photos_author_metadata_id"),
        "author_photos",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_photos_is_primary"),
        "author_photos",
        ["is_primary"],
        unique=False,
    )
    op.create_table(
        "author_remote_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_metadata_id", sa.Integer(), nullable=False),
        sa.Column(
            "identifier_type",
            sqlmodel.AutoString(length=50),
            nullable=False,
        ),
        sa.Column(
            "identifier_value",
            sqlmodel.AutoString(length=200),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_metadata_id"],
            ["author_metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "author_metadata_id", "identifier_type", name="uq_author_remote_id"
        ),
    )
    op.create_index(
        op.f("ix_author_remote_ids_author_metadata_id"),
        "author_remote_ids",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_remote_ids_identifier_type"),
        "author_remote_ids",
        ["identifier_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_remote_ids_identifier_value"),
        "author_remote_ids",
        ["identifier_value"],
        unique=False,
    )
    op.create_table(
        "author_similarities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author1_id", sa.Integer(), nullable=False),
        sa.Column("author2_id", sa.Integer(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column(
            "similarity_source",
            sqlmodel.AutoString(length=50),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author1_id"],
            ["author_metadata.id"],
        ),
        sa.ForeignKeyConstraint(
            ["author2_id"],
            ["author_metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("author1_id", "author2_id", name="uq_author_similarity"),
    )
    op.create_index(
        "idx_author_similarity_score",
        "author_similarities",
        ["author1_id", "similarity_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_similarities_author1_id"),
        "author_similarities",
        ["author1_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_similarities_author2_id"),
        "author_similarities",
        ["author2_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_similarities_created_at"),
        "author_similarities",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_author_similarities_created_at"), table_name="author_similarities"
    )
    op.drop_index(
        op.f("ix_author_similarities_author2_id"), table_name="author_similarities"
    )
    op.drop_index(
        op.f("ix_author_similarities_author1_id"), table_name="author_similarities"
    )
    op.drop_index("idx_author_similarity_score", table_name="author_similarities")
    op.drop_table("author_similarities")
    op.drop_index(
        op.f("ix_author_remote_ids_identifier_value"), table_name="author_remote_ids"
    )
    op.drop_index(
        op.f("ix_author_remote_ids_identifier_type"), table_name="author_remote_ids"
    )
    op.drop_index(
        op.f("ix_author_remote_ids_author_metadata_id"), table_name="author_remote_ids"
    )
    op.drop_table("author_remote_ids")
    op.drop_index(op.f("ix_author_photos_is_primary"), table_name="author_photos")
    op.drop_index(
        op.f("ix_author_photos_author_metadata_id"), table_name="author_photos"
    )
    op.drop_table("author_photos")
    op.drop_index(op.f("ix_author_mappings_is_verified"), table_name="author_mappings")
    op.drop_index(
        op.f("ix_author_mappings_calibre_author_id"), table_name="author_mappings"
    )
    op.drop_index(
        op.f("ix_author_mappings_author_metadata_id"), table_name="author_mappings"
    )
    op.drop_index("idx_author_mapping_verified", table_name="author_mappings")
    op.drop_index("idx_author_mapping_metadata", table_name="author_mappings")
    op.drop_index("idx_author_mapping_calibre", table_name="author_mappings")
    op.drop_index(op.f("ix_author_mappings_library_id"), table_name="author_mappings")
    op.drop_table("author_mappings")
    op.drop_index(op.f("ix_author_links_author_metadata_id"), table_name="author_links")
    op.drop_table("author_links")
    op.drop_index(
        op.f("ix_author_alternate_names_name"), table_name="author_alternate_names"
    )
    op.drop_index(
        op.f("ix_author_alternate_names_author_metadata_id"),
        table_name="author_alternate_names",
    )
    op.drop_table("author_alternate_names")
    op.drop_index(
        op.f("ix_author_metadata_openlibrary_key"), table_name="author_metadata"
    )
    op.drop_index(op.f("ix_author_metadata_name"), table_name="author_metadata")
    op.drop_index(op.f("ix_author_metadata_created_at"), table_name="author_metadata")
    op.drop_index("idx_author_metadata_openlibrary_key", table_name="author_metadata")
    op.drop_index("idx_author_metadata_name", table_name="author_metadata")
    op.drop_table("author_metadata")
    # ### end Alembic commands ###
