# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add cascade relationship to library fkey.

Revision ID: e142ce95cf2f
Revises: 9cb57048d879
Create Date: 2025-11-25 09:38:47.750189

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e142ce95cf2f"
down_revision: str | Sequence[str] | None = "9cb57048d879"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "annotations", "library_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("annotations_library_id_fkey"), "annotations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "annotations", "libraries", ["library_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "annotations_dirtied", "library_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("annotations_dirtied_library_id_fkey"),
        "annotations_dirtied",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "annotations_dirtied",
        "libraries",
        ["library_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "author_mappings", "library_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("author_mappings_library_id_fkey"), "author_mappings", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "author_mappings", "libraries", ["library_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "library_scan_states", "library_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("library_scan_states_library_id_fkey"),
        "library_scan_states",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "library_scan_states",
        "libraries",
        ["library_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "read_status", "library_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index("idx_read_status_status", "read_status", ["status"], unique=False)
    op.drop_constraint(
        op.f("read_status_library_id_fkey"), "read_status", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "read_status", "libraries", ["library_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "reading_progress", "library_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("reading_progress_library_id_fkey"), "reading_progress", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "reading_progress",
        "libraries",
        ["library_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "reading_sessions", "library_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("reading_sessions_library_id_fkey"), "reading_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "reading_sessions",
        "libraries",
        ["library_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("shelves", "library_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("shelves_library_id_fkey"), "shelves", type_="foreignkey")
    op.create_foreign_key(
        None, "shelves", "libraries", ["library_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "book_shelf_links", "shelf_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("book_shelf_links_shelf_id_fkey"), "book_shelf_links", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "book_shelf_links",
        "shelves",
        ["shelf_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("shelves_library_id_fkey"), "shelves", type_="foreignkey")
    op.create_foreign_key(
        op.f("shelves_library_id_fkey"), "shelves", "libraries", ["library_id"], ["id"]
    )
    op.alter_column("shelves", "library_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(
        op.f("reading_sessions_library_id_fkey"), "reading_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("reading_sessions_library_id_fkey"),
        "reading_sessions",
        "libraries",
        ["library_id"],
        ["id"],
    )
    op.alter_column(
        "reading_sessions", "library_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("reading_progress_library_id_fkey"), "reading_progress", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("reading_progress_library_id_fkey"),
        "reading_progress",
        "libraries",
        ["library_id"],
        ["id"],
    )
    op.alter_column(
        "reading_progress", "library_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("read_status_library_id_fkey"), "read_status", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("read_status_library_id_fkey"),
        "read_status",
        "libraries",
        ["library_id"],
        ["id"],
    )
    op.drop_index("idx_read_status_status", table_name="read_status")
    op.alter_column(
        "read_status", "library_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("library_scan_states_library_id_fkey"),
        "library_scan_states",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("library_scan_states_library_id_fkey"),
        "library_scan_states",
        "libraries",
        ["library_id"],
        ["id"],
    )
    op.alter_column(
        "library_scan_states", "library_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("author_mappings_library_id_fkey"), "author_mappings", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("author_mappings_library_id_fkey"),
        "author_mappings",
        "libraries",
        ["library_id"],
        ["id"],
    )
    op.alter_column(
        "author_mappings", "library_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("annotations_dirtied_library_id_fkey"),
        "annotations_dirtied",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("annotations_dirtied_library_id_fkey"),
        "annotations_dirtied",
        "libraries",
        ["library_id"],
        ["id"],
    )
    op.alter_column(
        "annotations_dirtied", "library_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("annotations_library_id_fkey"), "annotations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("annotations_library_id_fkey"),
        "annotations",
        "libraries",
        ["library_id"],
        ["id"],
    )
    op.alter_column(
        "annotations", "library_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("book_shelf_links_shelf_id_fkey"), "book_shelf_links", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("book_shelf_links_shelf_id_fkey"),
        "book_shelf_links",
        "shelves",
        ["shelf_id"],
        ["id"],
    )
    op.alter_column(
        "book_shelf_links", "shelf_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
