# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add library scan provider config.

Revision ID: eef7233e099c
Revises: 72a9cf864626
Create Date: 2025-11-18 23:23:59.067090

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eef7233e099c"
down_revision: str | Sequence[str] | None = "72a9cf864626"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library_scan_provider_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider_name",
            sqlmodel.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("rate_limit_delay_seconds", sa.Float(), nullable=False),
        sa.Column("max_requests_per_minute", sa.Integer(), nullable=True),
        sa.Column("max_requests_per_hour", sa.Integer(), nullable=True),
        sa.Column("stale_data_max_age_days", sa.Integer(), nullable=True),
        sa.Column("stale_data_refresh_interval_days", sa.Integer(), nullable=True),
        sa.Column("max_works_per_author", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_library_scan_provider_config_created_at"),
        "library_scan_provider_config",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_library_scan_provider_config_enabled"),
        "library_scan_provider_config",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_library_scan_provider_config_provider_name"),
        "library_scan_provider_config",
        ["provider_name"],
        unique=True,
    )
    # ### end Alembic commands ###

    # Seed default configuration for OpenLibrary provider
    now = datetime.now(UTC)
    op.execute(
        sa.text(
            """
            INSERT INTO library_scan_provider_config (
                provider_name,
                rate_limit_delay_seconds,
                max_requests_per_minute,
                max_requests_per_hour,
                stale_data_max_age_days,
                stale_data_refresh_interval_days,
                max_works_per_author,
                enabled,
                created_at,
                updated_at
            ) VALUES (
                'openlibrary',
                0.5,
                60,
                3600,
                30,
                7,
                999999,
                true,
                :created_at,
                :updated_at
            )
            """
        ).bindparams(created_at=now, updated_at=now)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove seed data before dropping table
    op.execute(
        sa.text(
            "DELETE FROM library_scan_provider_config WHERE provider_name = 'openlibrary'"
        )
    )
    op.drop_index(
        op.f("ix_library_scan_provider_config_provider_name"),
        table_name="library_scan_provider_config",
    )
    op.drop_index(
        op.f("ix_library_scan_provider_config_enabled"),
        table_name="library_scan_provider_config",
    )
    op.drop_index(
        op.f("ix_library_scan_provider_config_created_at"),
        table_name="library_scan_provider_config",
    )
    op.drop_table("library_scan_provider_config")
    # ### end Alembic commands ###
