# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Make openlibrary_key nullable.

Revision ID: f1c9a933a49a
Revises: 0b9016e0b426
Create Date: 2025-11-21 15:01:14.188553

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1c9a933a49a"
down_revision: str | Sequence[str] | None = "0b9016e0b426"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "author_metadata",
        "openlibrary_key",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.create_index(
        "idx_author_similarity_score_author2",
        "author_similarities",
        ["author2_id", "similarity_score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_author_similarity_score_author2", table_name="author_similarities"
    )
    op.alter_column(
        "author_metadata",
        "openlibrary_key",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    # ### end Alembic commands ###
