# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add auto-ingest settings to library.

Revision ID: f3c0bccb04c2
Revises: 7171d8926c89
Create Date: 2025-11-29 22:00:07.116929

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3c0bccb04c2"
down_revision: str | Sequence[str] | None = "7171d8926c89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "libraries", sa.Column("auto_convert_on_ingest", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "libraries",
        sa.Column(
            "auto_convert_target_format", sqlmodel.AutoString(length=20), nullable=True
        ),
    )
    op.add_column(
        "libraries",
        sa.Column(
            "auto_convert_ignored_formats",
            sqlmodel.AutoString(length=500),
            nullable=True,
        ),
    )
    op.add_column(
        "libraries",
        sa.Column("auto_convert_backup_originals", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "libraries",
        sa.Column("epub_fixer_auto_fix_on_ingest", sa.Boolean(), nullable=False),
    )
    op.drop_column("scheduled_tasks_config", "epub_fixer_auto_fix_on_ingest")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("libraries", "auto_convert_backup_originals")
    op.drop_column("libraries", "auto_convert_ignored_formats")
    op.drop_column("libraries", "auto_convert_target_format")
    op.drop_column("libraries", "auto_convert_on_ingest")
    op.add_column(
        "scheduled_tasks_config",
        sa.Column("epub_fixer_auto_fix_on_ingest", sa.BOOLEAN(), nullable=False),
    )
    op.drop_column("libraries", "epub_fixer_auto_fix_on_ingest")
    # ### end Alembic commands ###
