# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""API schemas organized by domain.

This package contains Pydantic models for API request/response validation,
organized by domain to follow Single Responsibility Principle.

Modules:
    auth: User authentication and authorization schemas
    books: Book management and search schemas
    libraries: Library management schemas
    metadata: Metadata search schemas and events
"""

from __future__ import annotations

# Re-export all schemas for backward compatibility
from bookcard.api.schemas.auth import (
    AdminUserCreate,
    AdminUserUpdate,
    AuthConfigResponse,
    EmailServerConfigRead,
    EmailServerConfigUpdate,
    EReaderDeviceCreate,
    EReaderDeviceRead,
    EReaderDeviceUpdate,
    InviteValidationResponse,
    LoginRequest,
    LoginResponse,
    OIDCCallbackRequest,
    OpenLibraryDumpConfigRead,
    OpenLibraryDumpConfigUpdate,
    PasswordChangeRequest,
    PermissionCreate,
    PermissionRead,
    PermissionUpdate,
    ProfilePictureUpdateRequest,
    ProfileRead,
    ProfileUpdate,
    RoleCreate,
    RolePermissionGrant,
    RolePermissionRead,
    RolePermissionUpdate,
    RoleRead,
    RoleUpdate,
    ScheduledTasksConfigRead,
    ScheduledTasksConfigUpdate,
    SettingRead,
    SettingsRead,
    SettingUpdate,
    TokenResponse,
    UserCreate,
    UserRead,
    UserRoleAssign,
)
from bookcard.api.schemas.books import (
    BookBatchUploadResponse,
    BookBulkSendRequest,
    BookConvertRequest,
    BookConvertResponse,
    BookDeleteRequest,
    BookFilterRequest,
    BookFixEpubResponse,
    BookListResponse,
    BookMergeRecommendRequest,
    BookMergeRequest,
    BookRead,
    BookSendRequest,
    BookStripDrmResponse,
    BookUpdate,
    BookUploadResponse,
    CoverFromUrlRequest,
    CoverFromUrlResponse,
    FilterSuggestionsResponse,
    FormatMetadataResponse,
    SearchSuggestionItem,
    SearchSuggestionsResponse,
    TagLookupItem,
    TagLookupResponse,
)
from bookcard.api.schemas.config import BasicConfigRead, BasicConfigUpdate
from bookcard.api.schemas.conversion import (
    BookConversionListResponse,
    BookConversionRead,
    ConversionRequest,
)
from bookcard.api.schemas.epub_fixer import (
    EPUBFixBatchRequest,
    EPUBFixListResponse,
    EPUBFixRead,
    EPUBFixResponse,
    EPUBFixRollbackResponse,
    EPUBFixRunListResponse,
    EPUBFixRunRead,
    EPUBFixSingleRequest,
    EPUBFixStatisticsRead,
)
from bookcard.api.schemas.indexers import (
    IndexerCreate,
    IndexerListResponse,
    IndexerRead,
    IndexerStatusResponse,
    IndexerTestResponse,
    IndexerUpdate,
)
from bookcard.api.schemas.kcc import (
    KCCProfileCreate,
    KCCProfileRead,
    KCCProfileUpdate,
)
from bookcard.api.schemas.libraries import (
    LibraryCreate,
    LibraryRead,
    LibraryStats,
    LibraryUpdate,
)
from bookcard.api.schemas.metadata import (
    MetadataProviderCompletedEvent,
    MetadataProviderFailedEvent,
    MetadataProviderProgressEvent,
    MetadataProvidersResponse,
    MetadataProviderStartedEvent,
    MetadataSearchCompletedEvent,
    MetadataSearchEvent,
    MetadataSearchProgressEvent,
    MetadataSearchRequest,
    MetadataSearchResponse,
    MetadataSearchStartedEvent,
)
from bookcard.api.schemas.reading import (
    ReadingHistoryResponse,
    ReadingProgressCreate,
    ReadingProgressRead,
    ReadingSessionCreate,
    ReadingSessionEnd,
    ReadingSessionRead,
    ReadingSessionsListResponse,
    ReadStatusRead,
    ReadStatusUpdate,
    RecentReadsResponse,
)
from bookcard.api.schemas.scheduled_jobs import ScheduledJobRead, ScheduledJobUpdate
from bookcard.api.schemas.shelves import (
    BookShelfLinkRead,
    ShelfCreate,
    ShelfListResponse,
    ShelfRead,
    ShelfReorderRequest,
    ShelfUpdate,
)
from bookcard.api.schemas.tasks import (
    TaskCancelResponse,
    TaskListResponse,
    TaskRead,
    TaskStatisticsRead,
    TaskTypesResponse,
)
from bookcard.api.schemas.user_libraries import (
    UserLibraryAssign,
    UserLibraryRead,
    UserLibraryVisibilityUpdate,
)

__all__ = [
    "AdminUserCreate",
    "AdminUserUpdate",
    "AuthConfigResponse",
    "BasicConfigRead",
    "BasicConfigUpdate",
    "BookBatchUploadResponse",
    "BookBulkSendRequest",
    "BookConversionListResponse",
    "BookConversionRead",
    "BookConvertRequest",
    "BookConvertResponse",
    "BookDeleteRequest",
    "BookFilterRequest",
    "BookFixEpubResponse",
    "BookListResponse",
    "BookMergeRecommendRequest",
    "BookMergeRequest",
    "BookRead",
    "BookSendRequest",
    "BookShelfLinkRead",
    "BookStripDrmResponse",
    "BookUpdate",
    "BookUploadResponse",
    "ConversionRequest",
    "CoverFromUrlRequest",
    "CoverFromUrlResponse",
    "EPUBFixBatchRequest",
    "EPUBFixListResponse",
    "EPUBFixRead",
    "EPUBFixResponse",
    "EPUBFixRollbackResponse",
    "EPUBFixRunListResponse",
    "EPUBFixRunRead",
    "EPUBFixSingleRequest",
    "EPUBFixStatisticsRead",
    "EReaderDeviceCreate",
    "EReaderDeviceRead",
    "EReaderDeviceUpdate",
    "EmailServerConfigRead",
    "EmailServerConfigUpdate",
    "FilterSuggestionsResponse",
    "FormatMetadataResponse",
    "IndexerCreate",
    "IndexerListResponse",
    "IndexerRead",
    "IndexerStatusResponse",
    "IndexerTestResponse",
    "IndexerUpdate",
    "InviteValidationResponse",
    "KCCProfileCreate",
    "KCCProfileRead",
    "KCCProfileUpdate",
    "LibraryCreate",
    "LibraryRead",
    "LibraryStats",
    "LibraryUpdate",
    "LoginRequest",
    "LoginResponse",
    "MetadataProviderCompletedEvent",
    "MetadataProviderFailedEvent",
    "MetadataProviderProgressEvent",
    "MetadataProviderStartedEvent",
    "MetadataProvidersResponse",
    "MetadataSearchCompletedEvent",
    "MetadataSearchEvent",
    "MetadataSearchProgressEvent",
    "MetadataSearchRequest",
    "MetadataSearchResponse",
    "MetadataSearchStartedEvent",
    "OIDCCallbackRequest",
    "OpenLibraryDumpConfigRead",
    "OpenLibraryDumpConfigUpdate",
    "PasswordChangeRequest",
    "PermissionCreate",
    "PermissionRead",
    "PermissionUpdate",
    "ProfilePictureUpdateRequest",
    "ProfileRead",
    "ProfileUpdate",
    "ReadStatusRead",
    "ReadStatusUpdate",
    "ReadingHistoryResponse",
    "ReadingProgressCreate",
    "ReadingProgressRead",
    "ReadingSessionCreate",
    "ReadingSessionEnd",
    "ReadingSessionRead",
    "ReadingSessionsListResponse",
    "RecentReadsResponse",
    "RoleCreate",
    "RolePermissionGrant",
    "RolePermissionRead",
    "RolePermissionUpdate",
    "RoleRead",
    "RoleUpdate",
    "ScheduledJobRead",
    "ScheduledJobUpdate",
    "ScheduledTasksConfigRead",
    "ScheduledTasksConfigUpdate",
    "SearchSuggestionItem",
    "SearchSuggestionsResponse",
    "SettingRead",
    "SettingUpdate",
    "SettingsRead",
    "ShelfCreate",
    "ShelfListResponse",
    "ShelfRead",
    "ShelfReorderRequest",
    "ShelfUpdate",
    "TagLookupItem",
    "TagLookupResponse",
    "TaskCancelResponse",
    "TaskListResponse",
    "TaskRead",
    "TaskStatisticsRead",
    "TaskTypesResponse",
    "TokenResponse",
    "UserCreate",
    "UserLibraryAssign",
    "UserLibraryRead",
    "UserLibraryVisibilityUpdate",
    "UserRead",
    "UserRoleAssign",
]
