# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Database models for Bookcard."""

from bookcard.models.auth import (
    EBookFormat,
    EReaderDevice,
    Permission,
    RefreshToken,
    Role,
    RolePermission,
    User,
    UserRole,
    UserSetting,
)
from bookcard.models.author_metadata import (
    AuthorAlternateName,
    AuthorLink,
    AuthorMapping,
    AuthorMetadata,
    AuthorPhoto,
    AuthorRemoteId,
    AuthorSimilarity,
    AuthorWork,
    WorkSubject,
)
from bookcard.models.config import (
    BasicConfig,
    ContentRestrictionsConfig,
    EmailServerConfig,
    EmailServerType,
    EPUBFixerConfig,
    FileHandlingConfig,
    IntegrationConfig,
    LDAPConfig,
    Library,
    LogLevel,
    ScheduledTasksConfig,
    SecurityConfig,
    UIConfig,
)
from bookcard.models.conversion import (
    BookConversion,
    ConversionMethod,
    ConversionStatus,
)
from bookcard.models.core import (
    Author,
    Book,
    BookAuthorLink,
    BookLanguageLink,
    BookPublisherLink,
    BookRatingLink,
    BookSeriesLink,
    BookTagLink,
    Comment,
    Identifier,
    Language,
    Publisher,
    Rating,
    Series,
    Tag,
)
from bookcard.models.epub_fixer import (
    EPUBFix,
    EPUBFixRun,
    EPUBFixType,
)
from bookcard.models.ingest import (
    IngestAudit,
    IngestConfig,
    IngestHistory,
    IngestRetry,
    IngestStatus,
)
from bookcard.models.kcc_config import KCCConversionProfile
from bookcard.models.kobo import (
    KoboArchivedBook,
    KoboAuthToken,
    KoboBookmark,
    KoboReadingState,
    KoboStatistics,
    KoboSyncedBook,
)
from bookcard.models.library_scanning import LibraryScanState
from bookcard.models.media import ConversionOptions, Data
from bookcard.models.metadata_enforcement import (
    EnforcementStatus,
    MetadataEnforcementOperation,
)
from bookcard.models.openlibrary import (
    OpenLibraryAuthor,
    OpenLibraryAuthorWork,
    OpenLibraryEdition,
    OpenLibraryEditionIsbn,
    OpenLibraryWork,
)
from bookcard.models.pvr import (
    DownloadBlocklist,
    DownloadClientDefinition,
    DownloadClientStatus,
    DownloadClientType,
    DownloadDecisionDefaults,
    DownloadItem,
    DownloadItemStatus,
    DownloadRejectionReason,
    IndexerDefinition,
    IndexerProtocol,
    IndexerStatus,
    IndexerType,
    ProwlarrConfig,
    RejectionType,
    TrackedBook,
    TrackedBookStatus,
)
from bookcard.models.reading import (
    Annotation,
    AnnotationDirtied,
    ReadingProgress,
    ReadingSession,
    ReadStatus,
    ReadStatusEnum,
)
from bookcard.models.shelves import (
    BookShelfLink,
    Shelf,
    ShelfArchive,
)
from bookcard.models.system import (
    BookPluginData,
    CustomColumn,
    Feed,
    LibraryId,
    MetadataDirtied,
    Preference,
)
from bookcard.models.tasks import (
    Task,
    TaskStatistics,
    TaskStatus,
    TaskType,
)

__all__ = [
    "Annotation",
    "AnnotationDirtied",
    "Author",
    "AuthorAlternateName",
    "AuthorLink",
    "AuthorMapping",
    "AuthorMetadata",
    "AuthorPhoto",
    "AuthorRemoteId",
    "AuthorSimilarity",
    "AuthorWork",
    "BasicConfig",
    "Book",
    "BookAuthorLink",
    "BookConversion",
    "BookLanguageLink",
    "BookPluginData",
    "BookPublisherLink",
    "BookRatingLink",
    "BookSeriesLink",
    "BookShelfLink",
    "BookTagLink",
    "Comment",
    "ContentRestrictionsConfig",
    "ConversionMethod",
    "ConversionOptions",
    "ConversionStatus",
    "CustomColumn",
    "Data",
    "DownloadBlocklist",
    "DownloadClientDefinition",
    "DownloadClientStatus",
    "DownloadClientType",
    "DownloadDecisionDefaults",
    "DownloadItem",
    "DownloadItemStatus",
    "DownloadRejectionReason",
    "EBookFormat",
    "EPUBFix",
    "EPUBFixRun",
    "EPUBFixType",
    "EPUBFixerConfig",
    "EReaderDevice",
    "EmailServerConfig",
    "EmailServerType",
    "EnforcementStatus",
    "Feed",
    "FileHandlingConfig",
    "Identifier",
    "IndexerDefinition",
    "IndexerProtocol",
    "IndexerStatus",
    "IndexerType",
    "IngestAudit",
    "IngestConfig",
    "IngestHistory",
    "IngestRetry",
    "IngestStatus",
    "IntegrationConfig",
    "KCCConversionProfile",
    "KoboArchivedBook",
    "KoboAuthToken",
    "KoboBookmark",
    "KoboReadingState",
    "KoboStatistics",
    "KoboSyncedBook",
    "LDAPConfig",
    "Language",
    "Library",
    "LibraryId",
    "LibraryScanState",
    "LogLevel",
    "MetadataDirtied",
    "MetadataEnforcementOperation",
    "OpenLibraryAuthor",
    "OpenLibraryAuthorWork",
    "OpenLibraryEdition",
    "OpenLibraryEditionIsbn",
    "OpenLibraryWork",
    "Permission",
    "Preference",
    "ProwlarrConfig",
    "Publisher",
    "Rating",
    "ReadStatus",
    "ReadStatusEnum",
    "ReadingProgress",
    "ReadingSession",
    "RefreshToken",
    "RejectionType",
    "Role",
    "RolePermission",
    "ScheduledTasksConfig",
    "SecurityConfig",
    "Series",
    "Shelf",
    "ShelfArchive",
    "Tag",
    "Task",
    "TaskStatistics",
    "TaskStatus",
    "TaskType",
    "TrackedBook",
    "TrackedBookStatus",
    "UIConfig",
    "User",
    "UserRole",
    "UserSetting",
    "WorkSubject",
]
