# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add trackedbook file.

Revision ID: 05455ccd6011
Revises: e4d667111efd
Create Date: 2026-01-02 10:45:25.842411

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05455ccd6011"
down_revision: str | Sequence[str] | None = "e4d667111efd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracked_book_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracked_book_id", sa.Integer(), nullable=False),
        sa.Column("path", sqlmodel.AutoString(length=2000), nullable=False),
        sa.Column("filename", sqlmodel.AutoString(length=500), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_type", sqlmodel.AutoString(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tracked_book_id"], ["tracked_books.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tracked_book_files_created_at"),
        "tracked_book_files",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_book_files_tracked_book_id"),
        "tracked_book_files",
        ["tracked_book_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tracked_book_files_tracked_book_id"), table_name="tracked_book_files"
    )
    op.drop_index(
        op.f("ix_tracked_book_files_created_at"), table_name="tracked_book_files"
    )
    op.drop_table("tracked_book_files")
    # ### end Alembic commands ###
