# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add kcc config profile.

Revision ID: 0d79a2423779
Revises: 97f0642dab85
Create Date: 2025-12-08 10:38:53.428757

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d79a2423779"
down_revision: str | Sequence[str] | None = "97f0642dab85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kcc_conversion_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("device_profile", sqlmodel.AutoString(length=10), nullable=False),
        sa.Column("output_format", sqlmodel.AutoString(length=10), nullable=False),
        sa.Column("manga_style", sa.Boolean(), nullable=False),
        sa.Column("hq", sa.Boolean(), nullable=False),
        sa.Column("two_panel", sa.Boolean(), nullable=False),
        sa.Column("webtoon", sa.Boolean(), nullable=False),
        sa.Column("upscale", sa.Boolean(), nullable=False),
        sa.Column("stretch", sa.Boolean(), nullable=False),
        sa.Column("gamma", sa.Float(), nullable=True),
        sa.Column("autolevel", sa.Boolean(), nullable=False),
        sa.Column("autocontrast", sa.Boolean(), nullable=False),
        sa.Column("colorautocontrast", sa.Boolean(), nullable=False),
        sa.Column("cropping", sa.Integer(), nullable=False),
        sa.Column("cropping_power", sa.Float(), nullable=False),
        sa.Column("preserve_margin", sa.Float(), nullable=False),
        sa.Column("cropping_minimum", sa.Float(), nullable=False),
        sa.Column("inter_panel_crop", sa.Integer(), nullable=False),
        sa.Column("black_borders", sa.Boolean(), nullable=False),
        sa.Column("white_borders", sa.Boolean(), nullable=False),
        sa.Column("force_color", sa.Boolean(), nullable=False),
        sa.Column("force_png", sa.Boolean(), nullable=False),
        sa.Column("mozjpeg", sa.Boolean(), nullable=False),
        sa.Column("maximize_strips", sa.Boolean(), nullable=False),
        sa.Column("splitter", sa.Integer(), nullable=False),
        sa.Column("target_size", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "is_default", name="uq_user_default_kcc_profile"
        ),
    )
    op.create_index(
        "idx_kcc_profiles_user", "kcc_conversion_profiles", ["user_id"], unique=False
    )
    op.create_index(
        "idx_kcc_profiles_user_default",
        "kcc_conversion_profiles",
        ["user_id", "is_default"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kcc_conversion_profiles_created_at"),
        "kcc_conversion_profiles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kcc_conversion_profiles_is_default"),
        "kcc_conversion_profiles",
        ["is_default"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kcc_conversion_profiles_name"),
        "kcc_conversion_profiles",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kcc_conversion_profiles_updated_at"),
        "kcc_conversion_profiles",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kcc_conversion_profiles_user_id"),
        "kcc_conversion_profiles",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_kcc_conversion_profiles_user_id"), table_name="kcc_conversion_profiles"
    )
    op.drop_index(
        op.f("ix_kcc_conversion_profiles_updated_at"),
        table_name="kcc_conversion_profiles",
    )
    op.drop_index(
        op.f("ix_kcc_conversion_profiles_name"), table_name="kcc_conversion_profiles"
    )
    op.drop_index(
        op.f("ix_kcc_conversion_profiles_is_default"),
        table_name="kcc_conversion_profiles",
    )
    op.drop_index(
        op.f("ix_kcc_conversion_profiles_created_at"),
        table_name="kcc_conversion_profiles",
    )
    op.drop_index("idx_kcc_profiles_user_default", table_name="kcc_conversion_profiles")
    op.drop_index("idx_kcc_profiles_user", table_name="kcc_conversion_profiles")
    op.drop_table("kcc_conversion_profiles")
    # ### end Alembic commands ###
