# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add download decision models.

Revision ID: 132c759984a6
Revises: 904a6f393fbc
Create Date: 2025-12-25 10:00:17.499210

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "132c759984a6"
down_revision: str | Sequence[str] | None = "904a6f393fbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_decision_defaults",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("preferred_formats", sa.JSON(), nullable=True),
        sa.Column("min_size_bytes", sa.Integer(), nullable=True),
        sa.Column("max_size_bytes", sa.Integer(), nullable=True),
        sa.Column("min_seeders", sa.Integer(), nullable=True),
        sa.Column("min_leechers", sa.Integer(), nullable=True),
        sa.Column("max_age_days", sa.Integer(), nullable=True),
        sa.Column("min_age_days", sa.Integer(), nullable=True),
        sa.Column("exclude_keywords", sa.JSON(), nullable=True),
        sa.Column("require_keywords", sa.JSON(), nullable=True),
        sa.Column("require_title_match", sa.Boolean(), nullable=False),
        sa.Column("require_author_match", sa.Boolean(), nullable=False),
        sa.Column("require_isbn_match", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_download_decision_defaults_created_at"),
        "download_decision_defaults",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "download_blocklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "download_url",
            sqlmodel.AutoString(length=2000),
            nullable=False,
        ),
        sa.Column("reason", sqlmodel.AutoString(length=255), nullable=True),
        sa.Column("tracked_book_id", sa.Integer(), nullable=True),
        sa.Column("indexer_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["indexer_id"], ["indexer_definitions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tracked_book_id"], ["tracked_books.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_blocklist_created", "download_blocklist", ["created_at"], unique=False
    )
    op.create_index(
        "idx_blocklist_indexer", "download_blocklist", ["indexer_id"], unique=False
    )
    op.create_index(
        "idx_blocklist_tracked_book",
        "download_blocklist",
        ["tracked_book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_blocklist_created_at"),
        "download_blocklist",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_blocklist_download_url"),
        "download_blocklist",
        ["download_url"],
        unique=True,
    )
    op.create_index(
        op.f("ix_download_blocklist_indexer_id"),
        "download_blocklist",
        ["indexer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_blocklist_tracked_book_id"),
        "download_blocklist",
        ["tracked_book_id"],
        unique=False,
    )
    op.add_column(
        "tracked_books", sa.Column("exclude_keywords", sa.JSON(), nullable=True)
    )
    op.add_column(
        "tracked_books", sa.Column("require_keywords", sa.JSON(), nullable=True)
    )
    op.add_column(
        "tracked_books", sa.Column("require_title_match", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "tracked_books", sa.Column("require_author_match", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "tracked_books", sa.Column("require_isbn_match", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_books", "require_isbn_match")
    op.drop_column("tracked_books", "require_author_match")
    op.drop_column("tracked_books", "require_title_match")
    op.drop_column("tracked_books", "require_keywords")
    op.drop_column("tracked_books", "exclude_keywords")
    op.drop_index(
        op.f("ix_download_blocklist_tracked_book_id"), table_name="download_blocklist"
    )
    op.drop_index(
        op.f("ix_download_blocklist_indexer_id"), table_name="download_blocklist"
    )
    op.drop_index(
        op.f("ix_download_blocklist_download_url"), table_name="download_blocklist"
    )
    op.drop_index(
        op.f("ix_download_blocklist_created_at"), table_name="download_blocklist"
    )
    op.drop_index("idx_blocklist_tracked_book", table_name="download_blocklist")
    op.drop_index("idx_blocklist_indexer", table_name="download_blocklist")
    op.drop_index("idx_blocklist_created", table_name="download_blocklist")
    op.drop_table("download_blocklist")
    op.drop_index(
        op.f("ix_download_decision_defaults_created_at"),
        table_name="download_decision_defaults",
    )
    op.drop_table("download_decision_defaults")
    # ### end Alembic commands ###
