# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add books ingest tables.

Revision ID: 676e525dec3d
Revises: 0b59171fa89c
Create Date: 2025-11-27 15:38:37.304723

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "676e525dec3d"
down_revision: str | Sequence[str] | None = "0b59171fa89c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_path", sqlmodel.AutoString(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="ingeststatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("ingest_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "error_message",
            sqlmodel.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ingest_history_file_path", "ingest_history", ["file_path"], unique=False
    )
    op.create_index(
        "idx_ingest_history_status_created",
        "ingest_history",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_history_book_id"), "ingest_history", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_history_created_at"),
        "ingest_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_history_file_path"),
        "ingest_history",
        ["file_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_history_user_id"), "ingest_history", ["user_id"], unique=False
    )
    op.create_table(
        "ingest_audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("history_id", sa.Integer(), nullable=True),
        sa.Column("action", sqlmodel.AutoString(length=100), nullable=False),
        sa.Column("file_path", sqlmodel.AutoString(length=2000), nullable=False),
        sa.Column("audit_metadata", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["history_id"],
            ["ingest_history.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ingest_audit_action_timestamp",
        "ingest_audit",
        ["action", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_ingest_audit_history_id", "ingest_audit", ["history_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_audit_action"), "ingest_audit", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_audit_history_id"), "ingest_audit", ["history_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_audit_timestamp"), "ingest_audit", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_audit_user_id"), "ingest_audit", ["user_id"], unique=False
    )
    op.create_table(
        "ingest_retry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("history_id", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=False),
        sa.Column(
            "error_message",
            sqlmodel.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["history_id"],
            ["ingest_history.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ingest_retry_next_retry", "ingest_retry", ["next_retry_at"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_retry_created_at"), "ingest_retry", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_retry_history_id"), "ingest_retry", ["history_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_retry_next_retry_at"),
        "ingest_retry",
        ["next_retry_at"],
        unique=False,
    )
    op.create_table(
        "ingest_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingest_dir", sqlmodel.AutoString(length=2000), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata_fetch_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column("metadata_providers", sa.JSON(), nullable=True),
        sa.Column(
            "metadata_merge_strategy",
            sqlmodel.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("metadata_priority_order", sa.JSON(), nullable=True),
        sa.Column("supported_formats", sa.JSON(), nullable=True),
        sa.Column("ignore_patterns", sa.JSON(), nullable=True),
        sa.Column("retry_max_attempts", sa.Integer(), nullable=False),
        sa.Column("retry_backoff_seconds", sa.Integer(), nullable=False),
        sa.Column("process_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("auto_delete_after_ingest", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingest_config_created_at"),
        "ingest_config",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingest_retry_next_retry_at"), table_name="ingest_retry")
    op.drop_index(op.f("ix_ingest_retry_history_id"), table_name="ingest_retry")
    op.drop_index(op.f("ix_ingest_retry_created_at"), table_name="ingest_retry")
    op.drop_index("idx_ingest_retry_next_retry", table_name="ingest_retry")
    op.drop_table("ingest_retry")
    op.drop_index(op.f("ix_ingest_audit_user_id"), table_name="ingest_audit")
    op.drop_index(op.f("ix_ingest_audit_timestamp"), table_name="ingest_audit")
    op.drop_index(op.f("ix_ingest_audit_history_id"), table_name="ingest_audit")
    op.drop_index(op.f("ix_ingest_audit_action"), table_name="ingest_audit")
    op.drop_index("idx_ingest_audit_history_id", table_name="ingest_audit")
    op.drop_index("idx_ingest_audit_action_timestamp", table_name="ingest_audit")
    op.drop_table("ingest_audit")
    op.drop_index(op.f("ix_ingest_history_user_id"), table_name="ingest_history")
    op.drop_index(op.f("ix_ingest_history_file_path"), table_name="ingest_history")
    op.drop_index(op.f("ix_ingest_history_created_at"), table_name="ingest_history")
    op.drop_index(op.f("ix_ingest_history_book_id"), table_name="ingest_history")
    op.drop_index("idx_ingest_history_status_created", table_name="ingest_history")
    op.drop_index("idx_ingest_history_file_path", table_name="ingest_history")
    op.drop_table("ingest_history")
    op.drop_index(op.f("ix_ingest_config_created_at"), table_name="ingest_config")
    op.drop_table("ingest_config")
    # ### end Alembic commands ###
