# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add kobo sync tables.

Revision ID: 7171d8926c89
Revises: a1b2c3d4e5f6
Create Date: 2025-11-29 18:34:16.086453

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7171d8926c89"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Detect database dialect
    connection = op.get_bind()
    is_postgresql = connection.dialect.name == "postgresql"
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kobo_archived_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_kobo_archived_books_user_book",
        "kobo_archived_books",
        ["user_id", "book_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_kobo_archived_books_book_id"),
        "kobo_archived_books",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_archived_books_is_archived"),
        "kobo_archived_books",
        ["is_archived"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_archived_books_last_modified"),
        "kobo_archived_books",
        ["last_modified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_archived_books_user_id"),
        "kobo_archived_books",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "kobo_auth_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("auth_token", sqlmodel.AutoString(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kobo_auth_tokens_auth_token"),
        "kobo_auth_tokens",
        ["auth_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_kobo_auth_tokens_created_at"),
        "kobo_auth_tokens",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_auth_tokens_user_id"),
        "kobo_auth_tokens",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "kobo_reading_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.Column("priority_timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_kobo_reading_states_last_modified",
        "kobo_reading_states",
        ["last_modified"],
        unique=False,
    )
    op.create_index(
        "idx_kobo_reading_states_user_book",
        "kobo_reading_states",
        ["user_id", "book_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_kobo_reading_states_book_id"),
        "kobo_reading_states",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_reading_states_last_modified"),
        "kobo_reading_states",
        ["last_modified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_reading_states_priority_timestamp"),
        "kobo_reading_states",
        ["priority_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_reading_states_user_id"),
        "kobo_reading_states",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "kobo_synced_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_kobo_synced_books_user_book",
        "kobo_synced_books",
        ["user_id", "book_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_kobo_synced_books_book_id"),
        "kobo_synced_books",
        ["book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_synced_books_synced_at"),
        "kobo_synced_books",
        ["synced_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_synced_books_user_id"),
        "kobo_synced_books",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "kobo_bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reading_state_id", sa.Integer(), nullable=False),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column("content_source_progress_percent", sa.Float(), nullable=True),
        sa.Column(
            "location_value",
            sqlmodel.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("location_type", sqlmodel.AutoString(length=50), nullable=True),
        sa.Column(
            "location_source",
            sqlmodel.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reading_state_id"],
            ["kobo_reading_states.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kobo_bookmarks_last_modified"),
        "kobo_bookmarks",
        ["last_modified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_bookmarks_reading_state_id"),
        "kobo_bookmarks",
        ["reading_state_id"],
        unique=True,
    )
    op.create_table(
        "kobo_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reading_state_id", sa.Integer(), nullable=False),
        sa.Column("spent_reading_minutes", sa.Integer(), nullable=True),
        sa.Column("remaining_time_minutes", sa.Integer(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reading_state_id"],
            ["kobo_reading_states.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kobo_statistics_last_modified"),
        "kobo_statistics",
        ["last_modified"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kobo_statistics_reading_state_id"),
        "kobo_statistics",
        ["reading_state_id"],
        unique=True,
    )
    # SQLite requires batch operations for column type changes
    if is_postgresql:
        op.alter_column(
            "metadata_enforcement_operations",
            "error_message",
            existing_type=sa.TEXT(),
            type_=sqlmodel.AutoString(),
            existing_nullable=True,
        )
    else:
        # SQLite: Use batch operations to recreate table with new column type
        with op.batch_alter_table(
            "metadata_enforcement_operations", schema=None
        ) as batch_op:
            batch_op.alter_column(
                "error_message",
                existing_type=sa.TEXT(),
                type_=sqlmodel.AutoString(),
                existing_nullable=True,
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Detect database dialect
    connection = op.get_bind()
    is_postgresql = connection.dialect.name == "postgresql"
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires batch operations for column type changes
    if is_postgresql:
        op.alter_column(
            "metadata_enforcement_operations",
            "error_message",
            existing_type=sqlmodel.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
    else:
        # SQLite: Use batch operations to recreate table with old column type
        with op.batch_alter_table(
            "metadata_enforcement_operations", schema=None
        ) as batch_op:
            batch_op.alter_column(
                "error_message",
                existing_type=sqlmodel.AutoString(),
                type_=sa.TEXT(),
                existing_nullable=True,
            )
    op.drop_index(
        op.f("ix_kobo_statistics_reading_state_id"), table_name="kobo_statistics"
    )
    op.drop_index(
        op.f("ix_kobo_statistics_last_modified"), table_name="kobo_statistics"
    )
    op.drop_table("kobo_statistics")
    op.drop_index(
        op.f("ix_kobo_bookmarks_reading_state_id"), table_name="kobo_bookmarks"
    )
    op.drop_index(op.f("ix_kobo_bookmarks_last_modified"), table_name="kobo_bookmarks")
    op.drop_table("kobo_bookmarks")
    op.drop_index(op.f("ix_kobo_synced_books_user_id"), table_name="kobo_synced_books")
    op.drop_index(
        op.f("ix_kobo_synced_books_synced_at"), table_name="kobo_synced_books"
    )
    op.drop_index(op.f("ix_kobo_synced_books_book_id"), table_name="kobo_synced_books")
    op.drop_index("idx_kobo_synced_books_user_book", table_name="kobo_synced_books")
    op.drop_table("kobo_synced_books")
    op.drop_index(
        op.f("ix_kobo_reading_states_user_id"), table_name="kobo_reading_states"
    )
    op.drop_index(
        op.f("ix_kobo_reading_states_priority_timestamp"),
        table_name="kobo_reading_states",
    )
    op.drop_index(
        op.f("ix_kobo_reading_states_last_modified"), table_name="kobo_reading_states"
    )
    op.drop_index(
        op.f("ix_kobo_reading_states_book_id"), table_name="kobo_reading_states"
    )
    op.drop_index("idx_kobo_reading_states_user_book", table_name="kobo_reading_states")
    op.drop_index(
        "idx_kobo_reading_states_last_modified", table_name="kobo_reading_states"
    )
    op.drop_table("kobo_reading_states")
    op.drop_index(op.f("ix_kobo_auth_tokens_user_id"), table_name="kobo_auth_tokens")
    op.drop_index(op.f("ix_kobo_auth_tokens_created_at"), table_name="kobo_auth_tokens")
    op.drop_index(op.f("ix_kobo_auth_tokens_auth_token"), table_name="kobo_auth_tokens")
    op.drop_table("kobo_auth_tokens")
    op.drop_index(
        op.f("ix_kobo_archived_books_user_id"), table_name="kobo_archived_books"
    )
    op.drop_index(
        op.f("ix_kobo_archived_books_last_modified"), table_name="kobo_archived_books"
    )
    op.drop_index(
        op.f("ix_kobo_archived_books_is_archived"), table_name="kobo_archived_books"
    )
    op.drop_index(
        op.f("ix_kobo_archived_books_book_id"), table_name="kobo_archived_books"
    )
    op.drop_index("idx_kobo_archived_books_user_book", table_name="kobo_archived_books")
    op.drop_table("kobo_archived_books")
    # ### end Alembic commands ###
