# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add additional settings for epub fix tasks.

Revision ID: 74235b62d3e5
Revises: 1003fa69a604
Create Date: 2025-11-26 21:51:11.957549

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74235b62d3e5"
down_revision: str | Sequence[str] | None = "1003fa69a604"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epub_fixer_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("backup_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "backup_directory",
            sqlmodel.AutoString(length=1000),
            nullable=False,
        ),
        sa.Column(
            "default_language",
            sqlmodel.AutoString(length=10),
            nullable=False,
        ),
        sa.Column("skip_already_fixed", sa.Boolean(), nullable=False),
        sa.Column("skip_failed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Seed default configuration
    epub_fixer_config_table = sa.table(
        "epub_fixer_config",
        sa.column("enabled", sa.Boolean()),
        sa.column("backup_enabled", sa.Boolean()),
        sa.column("backup_directory", sqlmodel.AutoString(length=1000)),
        sa.column("default_language", sqlmodel.AutoString(length=10)),
        sa.column("skip_already_fixed", sa.Boolean()),
        sa.column("skip_failed", sa.Boolean()),
        sa.column("created_at", sa.DateTime()),
        sa.column("updated_at", sa.DateTime()),
    )
    connection = op.get_bind()
    connection.execute(
        sa.insert(epub_fixer_config_table).values(
            enabled=True,
            backup_enabled=True,
            backup_directory="/data/processed_books/fixed_originals",
            default_language="en",
            skip_already_fixed=True,
            skip_failed=True,
            created_at=sa.func.current_timestamp(),
            updated_at=sa.func.current_timestamp(),
        )
    )

    op.create_index(
        op.f("ix_epub_fixer_config_created_at"),
        "epub_fixer_config",
        ["created_at"],
        unique=False,
    )
    op.add_column(
        "epub_fix_runs", sa.Column("cancelled_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "scheduled_tasks_config",
        sa.Column(
            "epub_fixer_daily_scan",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "scheduled_tasks_config",
        sa.Column(
            "epub_fixer_auto_fix_on_ingest",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scheduled_tasks_config", "epub_fixer_auto_fix_on_ingest")
    op.drop_column("scheduled_tasks_config", "epub_fixer_daily_scan")
    op.drop_column("epub_fix_runs", "cancelled_at")
    op.drop_index(
        op.f("ix_epub_fixer_config_created_at"), table_name="epub_fixer_config"
    )
    op.drop_table("epub_fixer_config")
    # ### end Alembic commands ###
