# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add user-defined author tables.

Revision ID: 74bf2dbdfcad
Revises: f1c9a933a49a
Create Date: 2025-11-21 17:53:26.688301

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

from bookcard.models.openlibrary import JSONBType

# revision identifiers, used by Alembic.
revision: str = "74bf2dbdfcad"
down_revision: str | Sequence[str] | None = "f1c9a933a49a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author_user_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_metadata_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sqlmodel.AutoString(length=100), nullable=False),
        sa.Column("field_value", JSONBType(), nullable=True),
        sa.Column("is_user_defined", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_metadata_id"],
            ["author_metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "author_metadata_id", "field_name", name="uq_author_user_metadata"
        ),
    )
    op.create_index(
        "idx_author_user_metadata_field",
        "author_user_metadata",
        ["author_metadata_id", "field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_user_metadata_author_metadata_id"),
        "author_user_metadata",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_user_metadata_created_at"),
        "author_user_metadata",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_user_metadata_field_name"),
        "author_user_metadata",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_user_metadata_is_user_defined"),
        "author_user_metadata",
        ["is_user_defined"],
        unique=False,
    )
    op.create_table(
        "author_user_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_metadata_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sqlmodel.AutoString(length=1000), nullable=False),
        sa.Column("file_name", sqlmodel.AutoString(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sqlmodel.AutoString(length=100), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("source_url", sqlmodel.AutoString(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_metadata_id"],
            ["author_metadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_author_user_photo_primary",
        "author_user_photos",
        ["author_metadata_id", "is_primary"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_user_photos_author_metadata_id"),
        "author_user_photos",
        ["author_metadata_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_user_photos_created_at"),
        "author_user_photos",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_author_user_photos_is_primary"),
        "author_user_photos",
        ["is_primary"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_author_user_photos_is_primary"), table_name="author_user_photos"
    )
    op.drop_index(
        op.f("ix_author_user_photos_created_at"), table_name="author_user_photos"
    )
    op.drop_index(
        op.f("ix_author_user_photos_author_metadata_id"),
        table_name="author_user_photos",
    )
    op.drop_index("idx_author_user_photo_primary", table_name="author_user_photos")
    op.drop_table("author_user_photos")
    op.drop_index(
        op.f("ix_author_user_metadata_is_user_defined"),
        table_name="author_user_metadata",
    )
    op.drop_index(
        op.f("ix_author_user_metadata_field_name"), table_name="author_user_metadata"
    )
    op.drop_index(
        op.f("ix_author_user_metadata_created_at"), table_name="author_user_metadata"
    )
    op.drop_index(
        op.f("ix_author_user_metadata_author_metadata_id"),
        table_name="author_user_metadata",
    )
    op.drop_index("idx_author_user_metadata_field", table_name="author_user_metadata")
    op.drop_table("author_user_metadata")
    # ### end Alembic commands ###
