# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add prowlarr sync.

Revision ID: 8bcccde3ec48
Revises: 15be3904f041
Create Date: 2025-12-27 19:25:31.295167

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bcccde3ec48"
down_revision: str | Sequence[str] | None = "15be3904f041"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Detect database dialect
    connection = op.get_bind()
    is_postgresql = connection.dialect.name == "postgresql"

    # Define the enum type for task_type column with new value
    task_type_enum = sa.Enum(
        "BOOK_UPLOAD",
        "MULTI_BOOK_UPLOAD",
        "BOOK_CONVERT",
        "BOOK_STRIP_DRM",
        "EMAIL_SEND",
        "METADATA_BACKUP",
        "THUMBNAIL_GENERATE",
        "LIBRARY_SCAN",
        "AUTHOR_METADATA_FETCH",
        "OPENLIBRARY_DUMP_DOWNLOAD",
        "OPENLIBRARY_DUMP_INGEST",
        "EPUB_FIX_SINGLE",
        "EPUB_FIX_BATCH",
        "EPUB_FIX_DAILY_SCAN",
        "INGEST_DISCOVERY",
        "INGEST_BOOK",
        "PVR_DOWNLOAD_MONITOR",
        "PROWLARR_SYNC",
        name="tasktype",
        native_enum=False,
    )

    if is_postgresql:
        op.alter_column(
            "task_statistics",
            "task_type",
            existing_type=sa.VARCHAR(length=50),
            type_=task_type_enum,
            existing_nullable=False,
        )
        op.alter_column(
            "tasks",
            "task_type",
            existing_type=sa.VARCHAR(length=50),
            type_=task_type_enum,
            existing_nullable=False,
        )
        op.alter_column(
            "scheduled_job_definitions",
            "task_type",
            existing_type=sa.VARCHAR(length=50),
            type_=task_type_enum,
            existing_nullable=False,
        )
    else:
        # SQLite: Use batch operations to recreate table with new column type
        with op.batch_alter_table("task_statistics", schema=None) as batch_op:
            batch_op.alter_column(
                "task_type",
                existing_type=sa.VARCHAR(length=50),
                type_=task_type_enum,
                existing_nullable=False,
            )
        with op.batch_alter_table("tasks", schema=None) as batch_op:
            batch_op.alter_column(
                "task_type",
                existing_type=sa.VARCHAR(length=50),
                type_=task_type_enum,
                existing_nullable=False,
            )
        with op.batch_alter_table("scheduled_job_definitions", schema=None) as batch_op:
            batch_op.alter_column(
                "task_type",
                existing_type=sa.VARCHAR(length=50),
                type_=task_type_enum,
                existing_nullable=False,
            )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prowlarr_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("api_key", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sync_categories", sa.JSON(), nullable=True),
        sa.Column("sync_app_profiles", sa.JSON(), nullable=True),
        sa.Column("sync_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prowlarr_config_created_at"),
        "prowlarr_config",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prowlarr_config_enabled"), "prowlarr_config", ["enabled"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Detect database dialect
    connection = op.get_bind()
    is_postgresql = connection.dialect.name == "postgresql"

    # Define the enum type for task_type column (original values)
    task_type_enum = sa.Enum(
        "BOOK_UPLOAD",
        "MULTI_BOOK_UPLOAD",
        "BOOK_CONVERT",
        "BOOK_STRIP_DRM",
        "EMAIL_SEND",
        "METADATA_BACKUP",
        "THUMBNAIL_GENERATE",
        "LIBRARY_SCAN",
        "AUTHOR_METADATA_FETCH",
        "OPENLIBRARY_DUMP_DOWNLOAD",
        "OPENLIBRARY_DUMP_INGEST",
        "EPUB_FIX_SINGLE",
        "EPUB_FIX_BATCH",
        "EPUB_FIX_DAILY_SCAN",
        "INGEST_DISCOVERY",
        "INGEST_BOOK",
        "PVR_DOWNLOAD_MONITOR",
        name="tasktype",
        native_enum=False,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prowlarr_config_enabled"), table_name="prowlarr_config")
    op.drop_index(op.f("ix_prowlarr_config_created_at"), table_name="prowlarr_config")
    op.drop_table("prowlarr_config")
    # ### end Alembic commands ###

    if is_postgresql:
        op.alter_column(
            "task_statistics",
            "task_type",
            existing_type=sa.VARCHAR(length=50),
            type_=task_type_enum,
            existing_nullable=False,
        )
        op.alter_column(
            "tasks",
            "task_type",
            existing_type=sa.VARCHAR(length=50),
            type_=task_type_enum,
            existing_nullable=False,
        )
        op.alter_column(
            "scheduled_job_definitions",
            "task_type",
            existing_type=sa.VARCHAR(length=50),
            type_=task_type_enum,
            existing_nullable=False,
        )
    else:
        # SQLite: Use batch operations to recreate table with new column type
        with op.batch_alter_table("tasks", schema=None) as batch_op:
            batch_op.alter_column(
                "task_type",
                existing_type=sa.VARCHAR(length=50),
                type_=task_type_enum,
                existing_nullable=False,
            )
        with op.batch_alter_table("task_statistics", schema=None) as batch_op:
            batch_op.alter_column(
                "task_type",
                existing_type=sa.VARCHAR(length=50),
                type_=task_type_enum,
                existing_nullable=False,
            )
        with op.batch_alter_table("scheduled_job_definitions", schema=None) as batch_op:
            batch_op.alter_column(
                "task_type",
                existing_type=sa.VARCHAR(length=50),
                type_=task_type_enum,
                existing_nullable=False,
            )
