# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add pvr core models.

Revision ID: 904a6f393fbc
Revises: 3647a7e2d1ef
Create Date: 2025-12-22 12:59:11.566234

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "904a6f393fbc"
down_revision: str | Sequence[str] | None = "3647a7e2d1ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_client_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column(
            "client_type",
            sa.Enum(
                "QBITTORRENT",
                "TRANSMISSION",
                "DELUGE",
                "RTORRENT",
                "UTORRENT",
                "VUZE",
                "ARIA2",
                "FLOOD",
                "HADOUKEN",
                "FREEBOX_DOWNLOAD",
                "DOWNLOAD_STATION",
                "SABNZBD",
                "NZBGET",
                "NZBVORTEX",
                "PNEUMATIC",
                "TORRENT_BLACKHOLE",
                "USENET_BLACKHOLE",
                name="downloadclienttype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("host", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.AutoString(length=255), nullable=True),
        sa.Column("password", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("use_ssl", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("category", sqlmodel.AutoString(length=100), nullable=True),
        sa.Column(
            "download_path",
            sqlmodel.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("additional_settings", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "HEALTHY",
                "DEGRADED",
                "UNHEALTHY",
                "DISABLED",
                name="downloadclientstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_successful_connection_at", sa.DateTime(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_download_clients_enabled_priority",
        "download_client_definitions",
        ["enabled", "priority"],
        unique=False,
    )
    op.create_index(
        "idx_download_clients_status_checked",
        "download_client_definitions",
        ["status", "last_checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_client_definitions_client_type"),
        "download_client_definitions",
        ["client_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_client_definitions_created_at"),
        "download_client_definitions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_client_definitions_enabled"),
        "download_client_definitions",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_client_definitions_last_successful_connection_at"),
        "download_client_definitions",
        ["last_successful_connection_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_client_definitions_name"),
        "download_client_definitions",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_client_definitions_priority"),
        "download_client_definitions",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_client_definitions_status"),
        "download_client_definitions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "indexer_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(length=255), nullable=False),
        sa.Column(
            "indexer_type",
            sa.Enum(
                "TORZNAB",
                "NEWZNAB",
                "TORRENT_RSS",
                "USENET_RSS",
                "CUSTOM",
                name="indexertype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "protocol",
            sa.Enum("TORRENT", "USENET", name="indexerprotocol", native_enum=False),
            nullable=False,
        ),
        sa.Column("base_url", sqlmodel.AutoString(length=1000), nullable=False),
        sa.Column("api_key", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=True),
        sa.Column("additional_settings", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "HEALTHY",
                "DEGRADED",
                "UNHEALTHY",
                "DISABLED",
                name="indexerstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("last_successful_query_at", sa.DateTime(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_indexers_enabled_priority",
        "indexer_definitions",
        ["enabled", "priority"],
        unique=False,
    )
    op.create_index(
        "idx_indexers_status_checked",
        "indexer_definitions",
        ["status", "last_checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexer_definitions_created_at"),
        "indexer_definitions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexer_definitions_enabled"),
        "indexer_definitions",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexer_definitions_indexer_type"),
        "indexer_definitions",
        ["indexer_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexer_definitions_last_successful_query_at"),
        "indexer_definitions",
        ["last_successful_query_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexer_definitions_name"),
        "indexer_definitions",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexer_definitions_priority"),
        "indexer_definitions",
        ["priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexer_definitions_protocol"),
        "indexer_definitions",
        ["protocol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexer_definitions_status"),
        "indexer_definitions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "tracked_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.AutoString(length=500), nullable=False),
        sa.Column("author", sqlmodel.AutoString(length=500), nullable=False),
        sa.Column("isbn", sqlmodel.AutoString(length=20), nullable=True),
        sa.Column("library_id", sa.Integer(), nullable=True),
        sa.Column(
            "metadata_source_id",
            sqlmodel.AutoString(length=100),
            nullable=True,
        ),
        sa.Column(
            "metadata_external_id",
            sqlmodel.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "WANTED",
                "SEARCHING",
                "DOWNLOADING",
                "COMPLETED",
                "FAILED",
                "IGNORED",
                name="trackedbookstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("auto_search_enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_download_enabled", sa.Boolean(), nullable=False),
        sa.Column("preferred_formats", sa.JSON(), nullable=True),
        sa.Column("last_searched_at", sa.DateTime(), nullable=True),
        sa.Column("last_downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("matched_book_id", sa.Integer(), nullable=True),
        sa.Column("matched_library_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cover_url", sqlmodel.AutoString(length=2000), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("publisher", sqlmodel.AutoString(length=500), nullable=True),
        sa.Column("published_date", sqlmodel.AutoString(length=50), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["matched_library_id"], ["libraries.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tracked_books_auto_search",
        "tracked_books",
        ["auto_search_enabled", "status"],
        unique=False,
    )
    op.create_index(
        "idx_tracked_books_status_created",
        "tracked_books",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_tracked_books_title_author",
        "tracked_books",
        ["title", "author"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_books_author"), "tracked_books", ["author"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_books_auto_search_enabled"),
        "tracked_books",
        ["auto_search_enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_books_created_at"),
        "tracked_books",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_books_isbn"), "tracked_books", ["isbn"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_books_last_searched_at"),
        "tracked_books",
        ["last_searched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_books_library_id"),
        "tracked_books",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_books_matched_book_id"),
        "tracked_books",
        ["matched_book_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_books_matched_library_id"),
        "tracked_books",
        ["matched_library_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_books_status"), "tracked_books", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_books_title"), "tracked_books", ["title"], unique=False
    )
    op.create_table(
        "download_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracked_book_id", sa.Integer(), nullable=False),
        sa.Column("download_client_id", sa.Integer(), nullable=False),
        sa.Column("indexer_id", sa.Integer(), nullable=True),
        sa.Column(
            "client_item_id",
            sqlmodel.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.AutoString(length=500), nullable=False),
        sa.Column(
            "download_url",
            sqlmodel.AutoString(length=2000),
            nullable=False,
        ),
        sa.Column("file_path", sqlmodel.AutoString(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "DOWNLOADING",
                "PAUSED",
                "COMPLETED",
                "FAILED",
                "REMOVED",
                name="downloaditemstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("downloaded_bytes", sa.Integer(), nullable=True),
        sa.Column("download_speed_bytes_per_sec", sa.Float(), nullable=True),
        sa.Column("eta_seconds", sa.Integer(), nullable=True),
        sa.Column("quality", sqlmodel.AutoString(length=50), nullable=True),
        sa.Column("release_info", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["download_client_id"],
            ["download_client_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["indexer_id"], ["indexer_definitions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tracked_book_id"], ["tracked_books.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_download_items_client_item_id",
        "download_items",
        ["download_client_id", "client_item_id"],
        unique=False,
    )
    op.create_index(
        "idx_download_items_status_created",
        "download_items",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_download_items_tracked_book_status",
        "download_items",
        ["tracked_book_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_items_client_item_id"),
        "download_items",
        ["client_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_items_completed_at"),
        "download_items",
        ["completed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_items_created_at"),
        "download_items",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_items_download_client_id"),
        "download_items",
        ["download_client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_items_indexer_id"),
        "download_items",
        ["indexer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_items_progress"), "download_items", ["progress"], unique=False
    )
    op.create_index(
        op.f("ix_download_items_quality"), "download_items", ["quality"], unique=False
    )
    op.create_index(
        op.f("ix_download_items_started_at"),
        "download_items",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_download_items_status"), "download_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_download_items_title"), "download_items", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_download_items_tracked_book_id"),
        "download_items",
        ["tracked_book_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_download_items_tracked_book_id"), table_name="download_items"
    )
    op.drop_index(op.f("ix_download_items_title"), table_name="download_items")
    op.drop_index(op.f("ix_download_items_status"), table_name="download_items")
    op.drop_index(op.f("ix_download_items_started_at"), table_name="download_items")
    op.drop_index(op.f("ix_download_items_quality"), table_name="download_items")
    op.drop_index(op.f("ix_download_items_progress"), table_name="download_items")
    op.drop_index(op.f("ix_download_items_indexer_id"), table_name="download_items")
    op.drop_index(
        op.f("ix_download_items_download_client_id"), table_name="download_items"
    )
    op.drop_index(op.f("ix_download_items_created_at"), table_name="download_items")
    op.drop_index(op.f("ix_download_items_completed_at"), table_name="download_items")
    op.drop_index(op.f("ix_download_items_client_item_id"), table_name="download_items")
    op.drop_index("idx_download_items_tracked_book_status", table_name="download_items")
    op.drop_index("idx_download_items_status_created", table_name="download_items")
    op.drop_index("idx_download_items_client_item_id", table_name="download_items")
    op.drop_table("download_items")
    op.drop_index(op.f("ix_tracked_books_title"), table_name="tracked_books")
    op.drop_index(op.f("ix_tracked_books_status"), table_name="tracked_books")
    op.drop_index(
        op.f("ix_tracked_books_matched_library_id"), table_name="tracked_books"
    )
    op.drop_index(op.f("ix_tracked_books_matched_book_id"), table_name="tracked_books")
    op.drop_index(op.f("ix_tracked_books_library_id"), table_name="tracked_books")
    op.drop_index(op.f("ix_tracked_books_last_searched_at"), table_name="tracked_books")
    op.drop_index(op.f("ix_tracked_books_isbn"), table_name="tracked_books")
    op.drop_index(op.f("ix_tracked_books_created_at"), table_name="tracked_books")
    op.drop_index(
        op.f("ix_tracked_books_auto_search_enabled"), table_name="tracked_books"
    )
    op.drop_index(op.f("ix_tracked_books_author"), table_name="tracked_books")
    op.drop_index("idx_tracked_books_title_author", table_name="tracked_books")
    op.drop_index("idx_tracked_books_status_created", table_name="tracked_books")
    op.drop_index("idx_tracked_books_auto_search", table_name="tracked_books")
    op.drop_table("tracked_books")
    op.drop_index(
        op.f("ix_indexer_definitions_status"), table_name="indexer_definitions"
    )
    op.drop_index(
        op.f("ix_indexer_definitions_protocol"), table_name="indexer_definitions"
    )
    op.drop_index(
        op.f("ix_indexer_definitions_priority"), table_name="indexer_definitions"
    )
    op.drop_index(op.f("ix_indexer_definitions_name"), table_name="indexer_definitions")
    op.drop_index(
        op.f("ix_indexer_definitions_last_successful_query_at"),
        table_name="indexer_definitions",
    )
    op.drop_index(
        op.f("ix_indexer_definitions_indexer_type"), table_name="indexer_definitions"
    )
    op.drop_index(
        op.f("ix_indexer_definitions_enabled"), table_name="indexer_definitions"
    )
    op.drop_index(
        op.f("ix_indexer_definitions_created_at"), table_name="indexer_definitions"
    )
    op.drop_index("idx_indexers_status_checked", table_name="indexer_definitions")
    op.drop_index("idx_indexers_enabled_priority", table_name="indexer_definitions")
    op.drop_table("indexer_definitions")
    op.drop_index(
        op.f("ix_download_client_definitions_status"),
        table_name="download_client_definitions",
    )
    op.drop_index(
        op.f("ix_download_client_definitions_priority"),
        table_name="download_client_definitions",
    )
    op.drop_index(
        op.f("ix_download_client_definitions_name"),
        table_name="download_client_definitions",
    )
    op.drop_index(
        op.f("ix_download_client_definitions_last_successful_connection_at"),
        table_name="download_client_definitions",
    )
    op.drop_index(
        op.f("ix_download_client_definitions_enabled"),
        table_name="download_client_definitions",
    )
    op.drop_index(
        op.f("ix_download_client_definitions_created_at"),
        table_name="download_client_definitions",
    )
    op.drop_index(
        op.f("ix_download_client_definitions_client_type"),
        table_name="download_client_definitions",
    )
    op.drop_index(
        "idx_download_clients_status_checked", table_name="download_client_definitions"
    )
    op.drop_index(
        "idx_download_clients_enabled_priority",
        table_name="download_client_definitions",
    )
    op.drop_table("download_client_definitions")
    # ### end Alembic commands ###
