# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add magic shelf support.

Revision ID: a492c10341b8
Revises: b82a45801b30
Create Date: 2026-01-30 18:42:17.861540

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a492c10341b8"
down_revision: str | Sequence[str] | None = "b82a45801b30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column (works for both)
    with op.batch_alter_table("shelves") as batch_op:
        batch_op.add_column(sa.Column("filter_rules", sa.JSON(), nullable=True))

    # 2. Update Enum
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Postgres: Add value to existing enum type
        # We need to execute this outside of a transaction block if possible,
        # but Alembic runs in a transaction.
        # However, ALTER TYPE ... ADD VALUE cannot run inside a transaction block
        # in older Postgres versions. In newer ones (12+), it can.
        # Assuming we are on a reasonably modern Postgres.
        # If not, we'd need commit() here.
        op.execute("ALTER TYPE shelftypeenum ADD VALUE 'magic_shelf'")
    else:
        # SQLite (and others): Recreate table with new Enum definition
        with op.batch_alter_table("shelves") as batch_op:
            new_enum = sa.Enum(
                "shelf", "read_list", "magic_shelf", name="shelftypeenum"
            )
            old_enum = sa.Enum("shelf", "read_list", name="shelftypeenum")

            batch_op.alter_column(
                "shelf_type",
                type_=new_enum,
                existing_type=old_enum,
                nullable=False,
                server_default="shelf",
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop column (works for both)
    with op.batch_alter_table("shelves") as batch_op:
        batch_op.drop_column("filter_rules")

    # 2. Revert Enum
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Postgres: Enum values cannot be removed easily.
        # We must create a new type, swap it, and drop the old one.
        op.execute("ALTER TYPE shelftypeenum RENAME TO shelftypeenum_old")
        op.execute("CREATE TYPE shelftypeenum AS ENUM('shelf', 'read_list')")
        op.execute(
            "ALTER TABLE shelves ALTER COLUMN shelf_type TYPE shelftypeenum "
            "USING shelf_type::text::shelftypeenum"
        )
        op.execute("DROP TYPE shelftypeenum_old")
    else:
        # SQLite: Recreate table
        with op.batch_alter_table("shelves") as batch_op:
            old_enum = sa.Enum("shelf", "read_list", name="shelftypeenum")
            new_enum = sa.Enum(
                "shelf", "read_list", "magic_shelf", name="shelftypeenum"
            )

            batch_op.alter_column(
                "shelf_type",
                type_=old_enum,
                existing_type=new_enum,
                nullable=False,
                server_default="shelf",
            )
    # ### end Alembic commands ###
