# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add work metadata table.

Revision ID: a71f0722640d
Revises: 226a99cf4645
Create Date: 2025-11-21 11:47:21.423363

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

from bookcard.models.openlibrary import JSONBType

# revision identifiers, used by Alembic.
revision: str = "a71f0722640d"
down_revision: str | Sequence[str] | None = "226a99cf4645"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_key", sqlmodel.AutoString(length=50), nullable=False),
        sa.Column("title", sqlmodel.AutoString(length=2000), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("first_sentence", sa.Text(), nullable=True),
        sa.Column("first_publish_date", sqlmodel.AutoString(length=100), nullable=True),
        sa.Column("covers", JSONBType(), nullable=True),
        sa.Column("subjects", JSONBType(), nullable=True),
        sa.Column("subject_people", JSONBType(), nullable=True),
        sa.Column("subject_places", JSONBType(), nullable=True),
        sa.Column("links", JSONBType(), nullable=True),
        sa.Column("excerpts", JSONBType(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=True),
        sa.Column("latest_revision", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column("raw_data", JSONBType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_work_metadata_title", "work_metadata", ["title"], unique=False)
    op.create_index(
        "idx_work_metadata_work_key", "work_metadata", ["work_key"], unique=False
    )
    op.create_index(
        op.f("ix_work_metadata_created_at"),
        "work_metadata",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_metadata_title"), "work_metadata", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_work_metadata_work_key"), "work_metadata", ["work_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_metadata_work_key"), table_name="work_metadata")
    op.drop_index(op.f("ix_work_metadata_title"), table_name="work_metadata")
    op.drop_index(op.f("ix_work_metadata_created_at"), table_name="work_metadata")
    op.drop_index("idx_work_metadata_work_key", table_name="work_metadata")
    op.drop_index("idx_work_metadata_title", table_name="work_metadata")
    op.drop_table("work_metadata")
    # ### end Alembic commands ###
