# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add user_libraries table.

Revision ID: c1e626fc8d52
Revises: ade158238c51
Create Date: 2026-02-07 05:18:19.146421

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1e626fc8d52"
down_revision: str | Sequence[str] | None = "ade158238c51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_libraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "library_id", name="uq_user_library"),
    )
    op.create_index(
        op.f("ix_user_libraries_created_at"),
        "user_libraries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_libraries_library_id"),
        "user_libraries",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_libraries_user_active",
        "user_libraries",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_libraries_user_id"),
        "user_libraries",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_libraries_user_visible",
        "user_libraries",
        ["user_id", "is_visible"],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- Data migration ---
    # Populate user_libraries from the cartesian product of users x libraries.
    # Every user gets every library as visible.  The library whose
    # ``is_active`` flag is currently True becomes the active library for each
    # user (preserving single-library behaviour).
    conn = op.get_bind()
    now = datetime.now(UTC)

    users = conn.execute(sa.text("SELECT id FROM users")).fetchall()
    libraries = conn.execute(sa.text("SELECT id, is_active FROM libraries")).fetchall()

    if users and libraries:
        user_libraries_table = sa.table(
            "user_libraries",
            sa.column("user_id", sa.Integer),
            sa.column("library_id", sa.Integer),
            sa.column("is_visible", sa.Boolean),
            sa.column("is_active", sa.Boolean),
            sa.column("created_at", sa.DateTime),
            sa.column("updated_at", sa.DateTime),
        )
        rows = [
            {
                "user_id": user.id,
                "library_id": lib.id,
                "is_visible": True,
                "is_active": bool(lib.is_active),
                "created_at": now,
                "updated_at": now,
            }
            for user in users
            for lib in libraries
        ]
        op.bulk_insert(user_libraries_table, rows)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_libraries_user_visible", table_name="user_libraries")
    op.drop_index(op.f("ix_user_libraries_user_id"), table_name="user_libraries")
    op.drop_index("ix_user_libraries_user_active", table_name="user_libraries")
    op.drop_index(op.f("ix_user_libraries_library_id"), table_name="user_libraries")
    op.drop_index(op.f("ix_user_libraries_created_at"), table_name="user_libraries")
    op.drop_table("user_libraries")
    # ### end Alembic commands ###
