# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add series fields to tracked_books.

Revision ID: d1b45e88976b
Revises: 05455ccd6011
Create Date: 2026-01-10 10:07:14.282754

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1b45e88976b"
down_revision: str | Sequence[str] | None = "05455ccd6011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_books",
        sa.Column("series_name", sqlmodel.AutoString(length=500), nullable=True),
    )
    op.add_column(
        "tracked_books",
        sa.Column("series_index", sa.Float(), nullable=True),
    )
    op.create_index(
        op.f("ix_tracked_books_series_name"),
        "tracked_books",
        ["series_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracked_books_series_name"), table_name="tracked_books")
    op.drop_column("tracked_books", "series_index")
    op.drop_column("tracked_books", "series_name")
    # ### end Alembic commands ###
