# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add monitor mode.

Revision ID: e4d667111efd
Revises: 9cdddde4fd59
Create Date: 2026-01-01 11:35:39.522237

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4d667111efd"
down_revision: str | Sequence[str] | None = "9cdddde4fd59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_books",
        sa.Column(
            "monitor_mode",
            sa.Enum(
                "BOOK_ONLY", "SERIES", "AUTHOR", name="monitormode", native_enum=False
            ),
            nullable=False,
            server_default="BOOK_ONLY",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_books", "monitor_mode")
    # ### end Alembic commands ###
