# Copyright (C) 2025 knguyen and others
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Add shelf_type and read_list_metadata to shelves.

Revision ID: eacab3c0f1ab
Revises: 0d79a2423779
Create Date: 2025-12-09 09:27:24.297495
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eacab3c0f1ab"
down_revision: str | Sequence[str] | None = "0d79a2423779"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    shelf_type_enum = sa.Enum("shelf", "read_list", name="shelftypeenum")
    shelf_type_enum.create(op.get_bind(), checkfirst=True)

    # Add column with default value for existing rows
    op.add_column(
        "shelves",
        sa.Column(
            "shelf_type", shelf_type_enum, nullable=False, server_default="shelf"
        ),
    )
    op.create_index(
        op.f("ix_shelves_shelf_type"), "shelves", ["shelf_type"], unique=False
    )

    # Add read_list_metadata column
    op.add_column("shelves", sa.Column("read_list_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop read_list_metadata column
    op.drop_column("shelves", "read_list_metadata")
    op.drop_index(op.f("ix_shelves_shelf_type"), table_name="shelves")
    op.drop_column("shelves", "shelf_type")
    # Drop enum type
    sa.Enum(name="shelftypeenum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
